import type { BaseProps } from '../interface';
type Props = BaseProps & {
    line1: string;
    line2: string;
    actionIcon?: string;
    actionIconTheme?: string;
    actionIconFamilyClass?: string;
    actionIconFamilyPrefix?: string;
    representativeImage?: string;
    representativeIcon?: string;
    representativeIconTheme?: string;
    representativeIconHasCircle?: boolean;
    representativeIconFamilyClass?: string;
    representativeIconFamilyPrefix?: string;
    href?: string;
    hrefTarget?: string;
    onClick?: () => void;
};
export default function DQuickActionButton({ line1, line2, className, actionIcon, actionIconFamilyClass, actionIconFamilyPrefix, actionIconTheme, representativeImage, representativeIcon, representativeIconTheme, representativeIconHasCircle, representativeIconFamilyClass, representativeIconFamilyPrefix, onClick, href, hrefTarget, style, dataAttributes, }: Props): import("react/jsx-runtime").JSX.Element;
export {};
