import { Meta, StoryObj } from '@storybook/react';
import { DInputPassword } from '../../components';
declare const config: Meta<typeof DInputPassword>;
export default config;
type Story = StoryObj<typeof DInputPassword>;
export declare const Default: Story;
export declare const Value: Story;
export declare const Error: Story;
export declare const Confirm: Story;
export declare const Disabled: Story;
