import { Meta, StoryObj } from '@storybook/react';
import { DInput } from '../../components';
declare const config: Meta<typeof DInput>;
export default config;
declare type Story = StoryObj<typeof DInput>;
export declare const Default: Story;
export declare const Value: Story;
export declare const Error: Story;
export declare const Confirm: Story;
export declare const Disabled: Story;
export declare const Text: Story;
