import { Meta, StoryObj } from '@storybook/react';
import { DInputSearch } from '../../components';
declare const config: Meta<typeof DInputSearch>;
export default config;
type Story = StoryObj<typeof DInputSearch>;
export declare const Default: Story;
export declare const Value: Story;
export declare const Error: Story;
export declare const Confirm: Story;
export declare const Disabled: Story;
