import { Meta, StoryObj } from '@storybook/react';
import { MButton } from '../../components';
declare const config: Meta<typeof MButton>;
export default config;
declare type Story = StoryObj<typeof MButton>;
export declare const Primary: Story;
export declare const PrimaryHover: Story;
export declare const PrimaryFocus: Story;
export declare const PrimaryDisabled: Story;
export declare const PrimaryActive: Story;
export declare const PrimaryIconRight: Story;
export declare const PrimaryLoading: Story;
export declare const PrimaryLoadingIconRight: Story;
export declare const PrimarySm: Story;
export declare const PrimaryLg: Story;
export declare const Secondary: Story;
export declare const SecondaryHover: Story;
export declare const SecondaryFocus: Story;
export declare const SecondaryDisabled: Story;
export declare const SecondaryActive: Story;
export declare const SecondaryIconRight: Story;
export declare const SecondaryLoading: Story;
export declare const SecondaryLoadingIconRight: Story;
export declare const SecondarySm: Story;
export declare const SecondaryLg: Story;
export declare const Link: Story;
export declare const LinkHover: Story;
export declare const LinkFocus: Story;
export declare const LinkDisabled: Story;
export declare const LinkActive: Story;
export declare const LinkIconRight: Story;
export declare const LinkLoading: Story;
export declare const LinkLoadingIconRight: Story;
export declare const LinkSm: Story;
export declare const LinkLg: Story;
