import { Meta, StoryObj } from '@storybook/react';
import { MCard } from '../../components';
declare const config: Meta<typeof MCard>;
export default config;
declare type Story = StoryObj<typeof MCard>;
export declare const Default: Story;
export declare const HeaderAndBody: Story;
export declare const OnlyBody: Story;
export declare const TopImage: Story;
export declare const Horizontal: Story;
