import { Meta, StoryObj } from '@storybook/react';
import { MInputPassword } from '../../components';
declare const config: Meta<typeof MInputPassword>;
export default config;
declare type Story = StoryObj<typeof MInputPassword>;
export declare const Default: Story;
export declare const Value: Story;
export declare const Error: Story;
export declare const Confirm: Story;
export declare const Disabled: Story;
