import { Meta, StoryObj } from '@storybook/react';
import { MInputSearch } from '../../components';
declare const config: Meta<typeof MInputSearch>;
export default config;
declare type Story = StoryObj<typeof MInputSearch>;
export declare const Default: Story;
export declare const Value: Story;
export declare const Error: Story;
export declare const Confirm: Story;
export declare const Disabled: Story;
