import { Meta, StoryObj } from '@storybook/react';
import MPaginator from '../../components/MPaginator';
declare const meta: Meta<typeof MPaginator>;
export default meta;
declare type Story = StoryObj<typeof MPaginator>;
export declare const Default: Story;
export declare const LabelArrows: Story;
export declare const NoArrows: Story;
export declare const CustomCurrentPage: Story;
export declare const CustomMaxWidth: Story;
