import { Meta, StoryObj } from '@storybook/react';
import { MProgressBar } from '../../components';
declare const config: Meta<typeof MProgressBar>;
export default config;
declare type Story = StoryObj<typeof MProgressBar>;
export declare const Default: Story;
export declare const Stripped: Story;
export declare const Valueless: Story;
export declare const Zero: Story;
export declare const Two: Story;
export declare const TwoValueless: Story;
export declare const OneHundred: Story;
