/**
 * build.mjs — generates every token artefact from `tokens/`.
 *
 * Outputs, all into `dist/tokens/`:
 *
 *   dynamic.tokens.css    custom properties, layered, with the dark mode
 *   dynamic.tokens.scss   Sass variables, for consumers still on Sass
 *   dynamic.tokens.ts     typed names + primitive literals, for React
 *   dynamic.tokens.json   the DTCG contract, published to the CDN
 *   dynamic.figma.json    normalised payload for the Figma Variables REST API
 *
 * The direction of the flow is the whole point: `tokens/` is the source and
 * every one of these is derived. 2.x had it the other way round — the SCSS was
 * the source and the JSON was reverse-engineered out of compiled CSS, which is
 * why Figma could never write back.
 *
 * Usage: node scripts/tokens/build.mjs
 */

import { writeFileSync, mkdirSync, readFileSync } from 'fs';
import { resolve } from 'path';

import {
  loadModel, ROOT, modeIndexFor,
} from './lib/model.mjs';
import {
  cssDeclaration, cssValue, cssVarName, cssVarRef, scssVarName,
  figmaType, figmaValue, figmaName, camel,
} from './lib/emit.mjs';

const OUT_DIR = resolve(ROOT, 'dist/tokens');

const model = loadModel();
const { manifest } = model;
const prefix = manifest.prefix;

const { version: pkgVersion } = JSON.parse(readFileSync(resolve(ROOT, 'package.json'), 'utf8'));

// The rem divisor. Authored as a token so a client can rescale the whole
// system, and read here rather than hardcoded.
const rootFontSizeToken = model.byId.get(manifest.rootFontSizeToken);
if (!rootFontSizeToken) {
  throw new Error(`tokens: manifest.rootFontSizeToken "${manifest.rootFontSizeToken}" not found`);
}
const ctx = { prefix, rootFontSize: rootFontSizeToken.value.value };

const banner = (what) => `/*!
 * Dynamic Framework — ${what}
 * GENERATED by scripts/tokens/build.mjs. Do not edit.
 * Source of truth: tokens/ (DTCG). Contract ${manifest.contract}, library ${pkgVersion}.
 */
`;

/* ------------------------------------------------------------------ *
 * Collection / mode helpers
 * ------------------------------------------------------------------ */

const collection = (name) => model.collections.find((c) => c.name === name);
const defaultMode = (col) => col.modes.find((m) => m.default) ?? col.modes[0];

/** Collections in manifest order, with their default mode. */
const baseBlocks = model.collections.map((col) => ({ col, mode: defaultMode(col) }));

/* ------------------------------------------------------------------ *
 * CSS
 * ------------------------------------------------------------------ */

function emitCss() {
  const lines = [banner('design tokens')];

  lines.push(`@layer ${prefix}.tokens {`);

  // Base: primitives, the default (light) semantic mode, components.
  for (const { col, mode } of baseBlocks) {
    lines.push('');
    lines.push(`  /* ${col.name}${col.modes.length > 1 ? ` — mode "${mode.name}"` : ''} */`);
    lines.push('  :root {');
    for (const t of mode.tokens) lines.push(`    ${cssDeclaration(t, ctx)}`);
    lines.push('  }');
  }

  // Mode blocks.
  //
  // A theme must be switchable on a SUBTREE, not only on the document — a dark
  // panel inside a light page is an ordinary requirement, and a Storybook sheet
  // showing both modes at once is the case that surfaced it. So the selectors
  // are plain attribute selectors rather than `:root[...]`, and EVERY mode gets
  // one, the default included: a light subtree inside a dark page has to
  // re-assert the tokens dark changed, because it cannot inherit them from the
  // `:root` block that dark already overrode further up the tree.
  //
  // Each block carries only the tokens that actually DIFFER between modes.
  // `semantic/shared.json` feeds every mode — type roles, shape, stroke,
  // elevation and motion are all mode-invariant — so re-declaring them would
  // repeat about a fifth of the file per mode and bury the colours that change.
  //
  // The `prefers-color-scheme` block stays root-scoped and guarded with
  // `:not([data-df-theme="light"])`: it is the default "system" state, which is
  // what most visitors have, and an explicit light choice must beat a dark OS.
  for (const col of model.collections) {
    if (col.modes.length < 2) continue;

    const base = new Map(
      defaultMode(col).tokens.map((t) => [t.name, cssDeclaration(t, ctx)]),
    );

    // Computed across ALL modes so every block declares the same set and no
    // mode is left with a hole a sibling mode filled.
    const changed = new Set();
    for (const mode of col.modes) {
      for (const t of mode.tokens) {
        if (base.get(t.name) !== cssDeclaration(t, ctx)) changed.add(t.name);
      }
    }
    if (!changed.size) continue;

    for (const mode of col.modes) {
      const decls = mode.tokens
        .filter((t) => changed.has(t.name))
        .map((t) => cssDeclaration(t, ctx));
      if (!decls.length) continue;

      if (mode.prefersColorScheme) {
        lines.push('');
        lines.push(`  /* ${col.name} — mode "${mode.name}", following the OS */`);
        lines.push(`  @media (prefers-color-scheme: ${mode.prefersColorScheme}) {`);
        lines.push(`    :root:not([data-${prefix}-theme="light"]) {`);
        for (const d of decls) lines.push(`      ${d}`);
        lines.push('    }');
        lines.push('  }');
      }

      if (mode.selector) {
        lines.push('');
        lines.push(`  /* ${col.name} — mode "${mode.name}", explicit; any subtree */`);
        lines.push(`  ${mode.selector} {`);
        for (const d of decls) lines.push(`    ${d}`);
        lines.push('  }');
      }
    }
  }

  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

/* ------------------------------------------------------------------ *
 * SCSS
 * ------------------------------------------------------------------ */

function emitScss() {
  const lines = [banner('design tokens (Sass)')];
  lines.push('// Aliases point at the custom property, not at a literal, so that');
  lines.push('// overriding a token at runtime still reaches Sass consumers.');
  lines.push('');

  for (const { col, mode } of baseBlocks) {
    lines.push(`// ${col.name}`);
    for (const t of mode.tokens) {
      const value = t.alias ? cssVarRef(t.alias, prefix) : cssValue(t, ctx);
      lines.push(`${scssVarName(t, prefix)}: ${value};`);
    }
    lines.push('');
  }

  const all = baseBlocks.flatMap(({ mode }) => mode.tokens);
  lines.push(`$${prefix}-tokens: (`);
  for (const t of all) lines.push(`  "${t.name}": ${scssVarName(t, prefix)},`);
  lines.push(');');
  lines.push('');
  return lines.join('\n');
}

/* ------------------------------------------------------------------ *
 * TypeScript
 * ------------------------------------------------------------------ */

function emitTs() {
  const all = baseBlocks.flatMap(({ mode }) => mode.tokens);
  const lines = [banner('design tokens (TypeScript)')];

  lines.push('/** Every token name in the system. */');
  lines.push('export type TokenName =');
  all.forEach((t, i) => lines.push(`  | '${t.name}'${i === all.length - 1 ? ';' : ''}`));
  lines.push('');

  lines.push('/** Custom-property name for each token, for use in inline styles. */');
  lines.push('export const tokenVar = {');
  for (const t of all) lines.push(`  ${camel(t.name)}: '${cssVarName(t, ctx.prefix)}',`);
  lines.push('} as const;');
  lines.push('');

  lines.push('/**');
  lines.push(' * Literal values, primitives only. Semantic and component tokens are');
  lines.push(' * deliberately absent: their value depends on the active mode, so a');
  lines.push(' * build-time literal would be wrong in dark mode. Read those through');
  lines.push(' * `tokenVar` and let the cascade resolve them.');
  lines.push(' */');
  lines.push('export const primitive = {');
  for (const t of all) {
    if (t.layer !== 'primitive' || t.alias) continue;
    lines.push(`  ${camel(t.name)}: '${cssValue(t, ctx)}',`);
  }
  lines.push('} as const;');
  lines.push('');
  return lines.join('\n');
}

/* ------------------------------------------------------------------ *
 * DTCG contract
 * ------------------------------------------------------------------ */

function emitDtcg() {
  const doc = {
    $description: `Dynamic Framework design tokens. Contract ${manifest.contract}.`,
    $extensions: {
      'dev.dynamicframework.contract': {
        contract: manifest.contract,
        library: pkgVersion,
        prefix,
        generatedFrom: 'tokens/ (DTCG source of truth)',
        collections: model.collections.map((c) => ({
          name: c.name,
          layer: c.layer,
          modes: c.modes.map((m) => m.name),
          figmaPublish: c.figma.publish ?? false,
        })),
      },
    },
  };

  // Nests each mode's tokens back into a DTCG tree under its collection.
  for (const col of model.collections) {
    const colNode = { $description: col.description };
    for (const mode of col.modes) {
      const modeNode = {};
      for (const t of mode.tokens) {
        let node = modeNode;
        t.path.slice(0, -1).forEach((seg) => {
          node[seg] = node[seg] ?? {};
          node = node[seg];
        });
        const leaf = { $type: t.type, $value: t.value };
        if (t.description) leaf.$description = t.description;
        node[t.path[t.path.length - 1]] = leaf;
      }
      colNode[mode.name] = modeNode;
    }
    doc[col.name] = colNode;
  }
  return `${JSON.stringify(doc, null, 2)}\n`;
}

/* ------------------------------------------------------------------ *
 * Figma Variables payload
 * ------------------------------------------------------------------ */

function emitFigma() {
  const skipped = [];

  const variableCollections = model.collections
    .filter((col) => col.figma.publish !== false)
    .map((col) => {
      const modes = col.modes.map((m) => m.name);
      const variables = new Map();

      for (const mode of col.modes) {
        for (const t of mode.tokens) {
          if (t.figma.publish === false) {
            skipped.push({ id: t.id, reason: 'marked publish: false' });
            continue;
          }
          const type = figmaType(t.type);
          if (!type) {
            skipped.push({ id: t.id, reason: `$type "${t.type}" has no Figma variable type` });
            continue;
          }

          if (!variables.has(t.name)) {
            variables.set(t.name, {
              name: figmaName(t),
              resolvedType: type,
              description: t.description ?? '',
              // Primitives are created in Figma — an alias needs its target to
              // exist in the file — but kept out of the published library so
              // designers reach for the semantic layer instead.
              hiddenFromPublishing: col.figma.hiddenFromPublishing === true,
              valuesByMode: {},
            });
          }

          const entry = variables.get(t.name);
          entry.valuesByMode[mode.name] = t.alias
            ? { type: 'VARIABLE_ALIAS', id: t.alias.split('.').join('/') }
            : figmaValue(t);
        }
      }

      return {
        name: col.name,
        modes,
        defaultMode: (col.modes.find((m) => m.default) ?? col.modes[0]).name,
        variables: [...variables.values()],
      };
    });

  return `${JSON.stringify({
    $extensions: {
      'dev.dynamicframework.figma': {
        contract: manifest.contract,
        library: pkgVersion,
        note:
          'Aliases reference targets by variable NAME (slash-separated). '
          + 'figma-push.mjs resolves those to variable ids in a second pass, '
          + 'because the REST API needs ids and they only exist after creation.',
        skipped,
      },
    },
    variableCollections,
  }, null, 2)}\n`;
}

/* ------------------------------------------------------------------ *
 * Write
 * ------------------------------------------------------------------ */

mkdirSync(OUT_DIR, { recursive: true });

const artefacts = {
  'dynamic.tokens.css': emitCss(),
  'dynamic.tokens.scss': emitScss(),
  'dynamic.tokens.ts': emitTs(),
  'dynamic.tokens.json': emitDtcg(),
  'dynamic.figma.json': emitFigma(),
};

for (const [file, content] of Object.entries(artefacts)) {
  writeFileSync(resolve(OUT_DIR, file), content, 'utf8');
  const kb = (Buffer.byteLength(content, 'utf8') / 1024).toFixed(1);
  process.stdout.write(`tokens: dist/tokens/${file.padEnd(22)} ${kb.padStart(7)} KB\n`);
}

const total = model.collections.reduce(
  (n, c) => n + c.modes.reduce((m, mode) => m + mode.tokens.length, 0),
  0,
);
process.stdout.write(`tokens: ${total} token records across ${model.collections.length} collections\n`);
