import type { Locale } from 'date-fns';
import type { ReactDatePickerProps } from 'react-datepicker';
import type { BaseProps, ButtonVariant, ComponentSize, FamilyIconProps } from '../interface';
type Props<CustomModifierNames extends string = never, WithRange extends boolean | undefined = undefined> = BaseProps & FamilyIconProps & Omit<ReactDatePickerProps<CustomModifierNames, WithRange>, 'selected' | 'selectsRange' | 'locale'> & {
    date?: string | null;
    withMonthSelector?: boolean;
    selectsRange?: boolean;
    inputLabel?: string;
    inputAriaLabel?: string;
    inputActionAriaLabel?: string;
    iconInput?: string;
    inputId?: string;
    timeId?: string;
    timeLabel?: string;
    iconHeaderPrevMonth?: string;
    iconHeaderNextMonth?: string;
    headerPrevMonthAriaLabel?: string;
    headerNextMonthAriaLabel?: string;
    headerIconSize?: ComponentSize;
    headerButtonVariant?: ButtonVariant;
    headerButtonTheme?: string;
    locale?: Locale;
};
export default function DDatePicker<CustomModifierNames extends string = never, WithRange extends boolean | undefined = undefined>({ date, selectsRange, withMonthSelector, inputLabel, inputAriaLabel, inputActionAriaLabel, inputId, timeId, timeLabel, iconInput: iconInputProp, iconHeaderPrevMonth: iconHeaderPrevMonthProp, iconHeaderNextMonth: iconHeaderNextMonthProp, iconMaterialStyle: iconMaterialStyleProp, iconFamilyClass, iconFamilyPrefix, headerPrevMonthAriaLabel, headerNextMonthAriaLabel, headerIconSize, headerButtonVariant, headerButtonTheme, locale, className, style, ...props }: Props<CustomModifierNames, WithRange>): import("react/jsx-runtime").JSX.Element;
export {};
