import { Meta, StoryObj } from '@storybook/react';
import { DAlert } from '../../components';
declare const config: Meta<typeof DAlert>;
export default config;
type Story = StoryObj<typeof DAlert>;
export declare const Light: Story;
export declare const Dark: Story;
export declare const Success: Story;
export declare const Danger: Story;
export declare const Info: Story;
export declare const Warning: Story;
export declare const LightIcon: Story;
export declare const DarkIcon: Story;
export declare const SuccessIcon: Story;
export declare const DangerIcon: Story;
export declare const InfoIcon: Story;
export declare const WarningIcon: Story;
export declare const LightClose: Story;
export declare const DarkClose: Story;
export declare const SuccessClose: Story;
export declare const DangerClose: Story;
export declare const InfoClose: Story;
export declare const WarningClose: Story;
export declare const WithIcon: Story;
