import { Meta, StoryObj } from '@storybook/react';
import { DCard } from '../../components';
declare const config: Meta<typeof DCard>;
export default config;
type Story = StoryObj<typeof DCard>;
export declare const Default: Story;
export declare const HeaderAndBody: Story;
export declare const OnlyBody: Story;
export declare const TopImage: Story;
export declare const Horizontal: Story;
