import type { MouseEvent, ReactNode } from 'react';
import type { BaseProps, ButtonType, ButtonVariant, ComponentColor, ComponentSize, EndIconProps, InputState, StartIconProps } from '../interface';
type Props = BaseProps & StartIconProps & EndIconProps & {
    id?: string;
    color?: ComponentColor;
    size?: ComponentSize;
    variant?: ButtonVariant;
    state?: InputState;
    text?: string;
    children?: ReactNode;
    ariaLabel?: string;
    value?: string;
    type?: ButtonType;
    loadingText?: string;
    loading?: boolean;
    loadingAriaLabel?: string;
    disabled?: boolean;
    stopPropagationEnabled?: boolean;
    form?: string;
    onClick?: (event: MouseEvent<HTMLButtonElement>) => void;
};
export default function DButton({ color, size, variant, state, text, children, ariaLabel, iconStart, iconStartFamilyClass, iconStartFamilyPrefix, iconStartMaterialStyle, iconEnd, iconEndFamilyClass, iconEndFamilyPrefix, iconEndMaterialStyle, loadingText, value, type, loading, loadingAriaLabel, disabled, stopPropagationEnabled, className, style, form, dataAttributes, onClick, }: Props): import("react/jsx-runtime").JSX.Element;
export {};
