import type { ReactDatePickerProps } from 'react-datepicker';
import type { ButtonVariant, ComponentSize } from './interface';
type Props = Omit<ReactDatePickerProps, 'onChange' | 'selectsRange'> & {
    date: string;
    onChangeDate: (value: Date | [Date | null, Date | null] | null) => void;
    selectsRange?: boolean;
    withMonthSelector?: boolean;
    inputLabel?: string;
    inputIcon?: string;
    inputId?: string;
    timeId?: string;
    timeLabel?: string;
    headerDecreaseMonthIcon?: string;
    headerIncreaseMonthIcon?: string;
    headerIconSize?: ComponentSize;
    headerButtonVariant?: ButtonVariant;
    headerButtonTheme?: string;
};
export default function DDatePicker({ onChangeDate, date, selectsRange, withMonthSelector, inputLabel, inputIcon, inputId, timeId, timeLabel, headerDecreaseMonthIcon, headerIncreaseMonthIcon, headerIconSize, headerButtonVariant, headerButtonTheme, ...props }: Props): import("react/jsx-runtime").JSX.Element;
export {};
