import { ComponentProps } from 'react';
import { ButtonVariant, ComponentSize } from '@dynamic-framework/ui';
import { DButton } from './proxies';
declare type Props = {
    monthDate: Date;
    decreaseMonth: () => void;
    increaseMonth: () => void;
    changeMonth: (monthNumber: number) => void;
    changeYear: (yearNumber: number) => void;
    prevMonthButtonDisabled: boolean;
    nextMonthButtonDisabled: boolean;
    withMonthSelector: boolean;
    decreaseMonthIcon: string;
    increaseMonthIcon: string;
    iconSize: ComponentSize;
    buttonVariant: ButtonVariant;
    buttonTheme: string;
} & Omit<ComponentProps<typeof DButton>, 'iconStart' | 'onMClick' | 'isDisabled'>;
export default function DDatePickerHeader({ monthDate, changeMonth, changeYear, decreaseMonth, increaseMonth, prevMonthButtonDisabled, nextMonthButtonDisabled, withMonthSelector, decreaseMonthIcon, increaseMonthIcon, iconSize, buttonVariant, buttonTheme, }: Props): import("react/jsx-runtime").JSX.Element;
export {};
