import type { CSSProperties } from 'react';
type Props = {
    line1: string;
    line2: string;
    className?: string;
    actionLinkText?: string;
    actionLinkTheme?: string;
    actionIcon?: string;
    secondaryActionIcon?: string;
    actionIconFamilyClass?: string;
    actionIconFamilyPrefix?: string;
    representativeImage?: string;
    representativeIcon?: string;
    representativeIconTheme?: string;
    representativeIconHasCircle?: boolean;
    representativeIconFamilyClass?: string;
    representativeIconFamilyPrefix?: string;
    onClick?: () => void;
    onClickSecondary?: () => void;
    style?: CSSProperties;
};
export default function DQuickActionButton({ line1, line2, className, actionLinkText, actionLinkTheme, actionIcon, secondaryActionIcon, actionIconFamilyClass, actionIconFamilyPrefix, representativeImage, representativeIcon, representativeIconTheme, representativeIconHasCircle, representativeIconFamilyClass, representativeIconFamilyPrefix, onClick, onClickSecondary, style, }: Props): import("react/jsx-runtime").JSX.Element;
export {};
