import type { ComponentProps } from 'react';
import DButton from '../DButton';
import type { BaseProps, ButtonVariant, ComponentSize, FamilyIconProps } from '../interface';
type Props = BaseProps & FamilyIconProps & {
    locale?: Locale;
    monthDate: Date;
    decreaseMonth: () => void;
    increaseMonth: () => void;
    changeMonth: (monthNumber: number) => void;
    changeYear: (yearNumber: number) => void;
    prevMonthButtonDisabled: boolean;
    nextMonthButtonDisabled: boolean;
    withMonthSelector: boolean;
    iconPrevMonth: string;
    iconNextMonth: string;
    prevMonthAriaLabel?: string;
    nextMonthAriaLabel?: string;
    iconSize: ComponentSize;
    buttonVariant: ButtonVariant;
    buttonTheme: string;
} & Omit<ComponentProps<typeof DButton>, 'iconStart' | 'onMClick' | 'isDisabled'>;
export default function DDatePickerHeader({ monthDate, changeMonth, changeYear, decreaseMonth, increaseMonth, prevMonthButtonDisabled, nextMonthButtonDisabled, withMonthSelector, iconPrevMonth, iconNextMonth, iconFamilyClass, iconFamilyPrefix, iconMaterialStyle, prevMonthAriaLabel, nextMonthAriaLabel, iconSize, buttonVariant, buttonTheme, locale, style, className, }: Props): import("react/jsx-runtime").JSX.Element;
export {};
