import type { ComponentProps } from 'react';
import DButton from '../DButton';
import type { BaseProps, ButtonVariant, ComponentSize, FamilyIconProps } from '../interface';
type Props = BaseProps & FamilyIconProps & {
    locale?: Locale;
    date: Date;
    decreaseMonth: () => void;
    increaseMonth: () => void;
    changeMonth: (monthNumber: number) => void;
    changeYear: (yearNumber: number) => void;
    prevMonthButtonDisabled: boolean;
    nextMonthButtonDisabled: boolean;
    iconPrevMonth: string;
    iconNextMonth: string;
    prevMonthAriaLabel?: string;
    nextMonthAriaLabel?: string;
    iconSize: ComponentSize;
    buttonVariant: ButtonVariant;
    buttonTheme: string;
    minYearSelect: number;
    maxYearSelect: number;
} & Omit<ComponentProps<typeof DButton>, 'iconStart' | 'onClick' | 'disabled'>;
export default function DDatePickerHeader({ date, changeYear, changeMonth, decreaseMonth, increaseMonth, prevMonthButtonDisabled, nextMonthButtonDisabled, iconPrevMonth, iconNextMonth, iconFamilyClass, iconFamilyPrefix, iconMaterialStyle, prevMonthAriaLabel, nextMonthAriaLabel, iconSize, buttonVariant, buttonTheme, locale, style, className, minYearSelect, maxYearSelect, }: Props): import("react/jsx-runtime").JSX.Element;
export {};
