import type { Preview } from '@storybook/react';

export default {
  parameters: {
    layout: 'centered',
    actions: { argTypesRegex: '^on[A-Z].*' },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/,
      },
    },
    options: {
      storySort: {
        order: [
          'Design System',
          [
            'Tokens',
            [
              'Typography',
              'Colors',
              'Spacing',
              'Border',
              'Shadow',
              'Layout',
            ],
            'Components',
            [
              'Badge',
              'Box File',
              'Button',
              'Card',
              'Card Account',
              'Chip',
              'Datepicker',
              'Formik Input',
              'Formik Input Currency',
              'Formik Input Select',
              'Icon',
              'Input',
              'Input Check',
              'Input Counter',
              'Input Currency',
              'Input Currency Base',
              'Input Password',
              'Input Pin',
              'Input Search',
              'Input Select',
              'Input Switch',
              'List',
              'List Item',
              'List Item Movement',
              'Paginator',
              'Progress',
              'Quick Action Button',
              'Quick Action Check',
              'Quick Action Select',
              'Quick Action Switch',
              'Skeleton',
              'Stepper',
              'Stepper Desktop',
              'Stepper Mobile',
              'Tooltip',
              '*'
            ],
            'Patterns',
            [
              'Alert',
              'Modal',
              'Offcanvas',
              'Carousel',
              'Popover',
              'Tabs',
              'Collapse',
              'Collapse Icon Text',
            ],
          ],
        ],
      },
    },
  },
} as Preview;
