import type { MouseEvent } from 'react';
import type { BaseProps, ButtonType, ButtonVariant, ComponentSize, EndIconProps, InputState, StartIconProps } from '../interface';
type Props = BaseProps & StartIconProps & EndIconProps & {
    id?: string;
    theme?: string;
    size?: ComponentSize;
    variant?: ButtonVariant;
    state?: InputState;
    text?: string;
    ariaLabel?: string;
    value?: string;
    type?: ButtonType;
    pill?: boolean;
    loading?: boolean;
    loadingAriaLabel?: string;
    disabled?: boolean;
    isStopPropagationEnabled?: boolean;
    onClick?: (event: MouseEvent<HTMLButtonElement>) => void;
};
export default function DButton({ theme, size, variant, state, text, ariaLabel, iconStart, iconStartFamilyClass, iconStartFamilyPrefix, iconEnd, iconEndFamilyClass, iconEndFamilyPrefix, value, type, pill, loading, loadingAriaLabel, disabled, isStopPropagationEnabled, className, onClick, }: Props): import("react/jsx-runtime").JSX.Element;
export {};
