/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
import { IconSettings } from "./utils";
import { ButtonType, ButtonVariant } from "./components/m-button/m-button-interface";
import { FormControlLayoutDirection, InputState, NavegableProps } from "./utils/component-interface";
import { CouponEvent, CouponInputType } from "./components/m-coupon/m-coupon-interface";
import { CurrencyEvent, CurrencyVariant } from "./components/m-currency/m-currency-interface";
import { Options } from "currency.js";
import { FormCheckState, FormCheckType } from "./components/m-form-check/m-form-check-interface";
import { ListItemVariant, SelectableProps } from "./components/m-list-item/m-list-item-interface";
import { FullScreenFrom, ModalSize } from "./components/m-modal/m-modal-interface";
import { PositionToggleFrom } from "./components/m-offcanvas/m-offcanvas-interface";
import { QuickActionState, QuickActionVariant } from "./components/m-quick-action/m-quick-action-interface";
import { SelectLayoutVariant } from "./components/m-select/m-select-interface";
export namespace Components {
    interface MAlert {
        /**
          * Show close button
         */
        "showClose"?: boolean;
        /**
          * Show icon theme in the alert
         */
        "showIcon": boolean;
        /**
          * Theme for the alert
         */
        "theme": string;
    }
    interface MApp {
        /**
          * Icon settings
         */
        "iconSettings"?: IconSettings;
    }
    interface MBadge {
        /**
          * The text of badge
         */
        "text": string;
        /**
          * The theme to use.
         */
        "theme": string;
    }
    interface MButton {
        /**
          * Icon right to display
         */
        "iconEnd"?: string;
        /**
          * Icon right family class
         */
        "iconEndFamilyClass"?: string;
        /**
          * Icon right family prefix
         */
        "iconEndFamilyPrefix"?: string;
        /**
          * Icon left to display
         */
        "iconStart"?: string;
        /**
          * Icon left family class
         */
        "iconStartFamilyClass"?: string;
        /**
          * Icon left family prefix
         */
        "iconStartFamilyPrefix"?: string;
        /**
          * Flag for loading state and disable button.
         */
        "isLoading": boolean;
        /**
          * Flag to switch to pill button border radius.
         */
        "isPill": boolean;
        /**
          * Flag to set the button as active.
         */
        "state"?: InputState;
        /**
          * The text to display.
         */
        "text": string;
        /**
          * The theme to use.
         */
        "theme": string;
        /**
          * The type of the button.
         */
        "type": ButtonType;
        /**
          * The value of the button.
         */
        "value": string;
        /**
          * The variant to use.
         */
        "variant"?: ButtonVariant;
    }
    interface MCounter {
        /**
          * Hint text
         */
        "hint"?: string;
        /**
          * Right icon of the hint text
         */
        "hintIconEnd"?: string;
        /**
          * Hint right icon family class
         */
        "hintIconEndFamilyClass"?: string;
        /**
          * Hint right icon family class
         */
        "hintIconEndFamilyPrefix"?: string;
        /**
          * Left icon of the hint text
         */
        "hintIconStart"?: string;
        /**
          * Hint left icon family class
         */
        "hintIconStartFamilyClass"?: string;
        /**
          * Hint left icon family class
         */
        "hintIconStartFamilyPrefix"?: string;
        /**
          * Is disabled counter
         */
        "isDisabled": boolean;
        /**
          * Flag for loading state.
         */
        "isLoading": boolean;
        /**
          * Label of the input
         */
        "label"?: string;
        /**
          * Icon for the label text
         */
        "labelIcon": string;
        /**
          * Icon label family class
         */
        "labelIconFamilyClass"?: string;
        /**
          * Icon label family class
         */
        "labelIconFamilyPrefix"?: string;
        /**
          * Change the layout direction to put the label on top or left of input
         */
        "layoutDirection": FormControlLayoutDirection;
        /**
          * Id of the input
         */
        "mId": string;
        /**
          * Maximum value for the input
         */
        "maxValue": number;
        /**
          * Minimum value for the input
         */
        "minValue": number;
        /**
          * Theme of the counter
         */
        "theme"?: string;
        /**
          * Value of the input
         */
        "value": number;
        /**
          * Variant of the counter
         */
        "variant": 'default' | 'prime';
    }
    interface MCoupon {
        /**
          * Text for the coupon button
         */
        "buttonText": string;
        /**
          * Has a select input
         */
        "hasSelect": boolean;
        /**
          * Hint for the m-coupon
         */
        "hint"?: string;
        /**
          * Icon end for the hint text
         */
        "hintIconEnd"?: string;
        /**
          * Hint right icon family class
         */
        "hintIconEndFamilyClass"?: string;
        /**
          * Hint right icon family class
         */
        "hintIconEndFamilyPrefix"?: string;
        /**
          * Icon start for the hint text
         */
        "hintIconStart"?: string;
        /**
          * Hint left icon family class
         */
        "hintIconStartFamilyClass"?: string;
        /**
          * Hint left icon family class
         */
        "hintIconStartFamilyPrefix"?: string;
        /**
          * Icon of the end
         */
        "iconEnd"?: string;
        /**
          * Right icon family class
         */
        "iconEndFamilyClass"?: string;
        /**
          * Right icon family class
         */
        "iconEndFamilyPrefix"?: string;
        /**
          * Icon of the middle
         */
        "iconMiddle"?: string;
        /**
          * Middle icon family class
         */
        "iconMiddleFamilyClass"?: string;
        /**
          * Middle icon family class
         */
        "iconMiddleFamilyPrefix"?: string;
        /**
          * Icon of the left
         */
        "iconStart"?: string;
        /**
          * Left icon family class
         */
        "iconStartFamilyClass"?: string;
        /**
          * Left icon family class
         */
        "iconStartFamilyPrefix"?: string;
        /**
          * Flag for loading state.
         */
        "isLoading": boolean;
        /**
          * Label for the input
         */
        "label": string;
        /**
          * Icon for the label text
         */
        "labelIcon": string;
        /**
          * Icon label family class
         */
        "labelIconFamilyClass"?: string;
        /**
          * Icon label family class
         */
        "labelIconFamilyPrefix"?: string;
        /**
          * Change the layout direction to put the label on top or left of input
         */
        "layoutDirection": FormControlLayoutDirection;
        /**
          * Id for the input
         */
        "mId": string;
        /**
          * Placeholder for the input
         */
        "placeholder"?: string;
        /**
          * Theme for the m-cupon
         */
        "theme"?: string;
        /**
          * * The type of the input
         */
        "type": CouponInputType;
    }
    interface MCurrency {
        /**
          * Options for the m-currency
         */
        "currencyOptions": Options;
        /**
          * Hint text for the m-currency
         */
        "hint"?: string;
        /**
          * Icon end for the hint text
         */
        "hintIconEnd"?: string;
        /**
          * Hint right icon family class
         */
        "hintIconEndFamilyClass"?: string;
        /**
          * Hint right icon family class
         */
        "hintIconEndFamilyPrefix"?: string;
        /**
          * Icon start for the hint text
         */
        "hintIconStart"?: string;
        /**
          * Hint left icon family class
         */
        "hintIconStartFamilyClass"?: string;
        /**
          * Hint left icon family class
         */
        "hintIconStartFamilyPrefix"?: string;
        /**
          * Icon for the end
         */
        "iconEnd"?: string;
        /**
          * Right icon family class
         */
        "iconEndFamilyClass"?: string;
        /**
          * Right icon family class
         */
        "iconEndFamilyPrefix"?: string;
        /**
          * Icon for the middle
         */
        "iconMiddle"?: string;
        /**
          * Middle icon family class
         */
        "iconMiddleFamilyClass"?: string;
        /**
          * Middle icon family class
         */
        "iconMiddleFamilyPrefix"?: string;
        /**
          * Icon for the left
         */
        "iconStart"?: string;
        /**
          * Left icon family class
         */
        "iconStartFamilyClass"?: string;
        /**
          * Left icon family class
         */
        "iconStartFamilyPrefix"?: string;
        /**
          * The input is disabled
         */
        "isDisabled": boolean;
        /**
          * Flag for loading state.
         */
        "isLoading": boolean;
        /**
          * Label for the input
         */
        "label": string;
        /**
          * Callback to extract the label from the option
         */
        "labelExtractor": (item: any) => string;
        /**
          * Icon for the label text
         */
        "labelIcon": string;
        /**
          * Icon label family class
         */
        "labelIconFamilyClass"?: string;
        /**
          * Icon label family class
         */
        "labelIconFamilyPrefix"?: string;
        /**
          * Change the layout direction to put the label on top or left of input
         */
        "layoutDirection": FormControlLayoutDirection;
        /**
          * Id for the input
         */
        "mId": string;
        /**
          * * The max value of the input
         */
        "maxValue"?: number;
        /**
          * * The min value of the input
         */
        "minValue"?: number;
        /**
          * Placeholder for the input
         */
        "placeholder"?: string;
        /**
          * Select options
         */
        "selectOptions": Array<any>;
        /**
          * Theme for the m-currency
         */
        "theme"?: string;
        /**
          * * The value of the input
         */
        "value"?: number;
        /**
          * Callback to extract the value from the option
         */
        "valueExtractor": (item: any) => string | number;
        /**
          * Variant for the m-currency
         */
        "variant"?: CurrencyVariant;
    }
    interface MFormCheck {
        /**
          * Set checkbox as toggle button
         */
        "isButton": boolean;
        /**
          * Set checkbox or radio button marked as selected or not
         */
        "isChecked": boolean;
        /**
          * Set input as disabled
         */
        "isDisabled": boolean;
        /**
          * Set view of checkbox as indeterminated
         */
        "isIndeterminate"?: boolean;
        /**
          * Text that will be displayed beside Check input or Radio input
         */
        "label"?: string;
        /**
          * Form control identifier
         */
        "mId": string;
        /**
          * HTML Name to use within a form or JS reference
         */
        "name"?: string;
        /**
          * State of checkbox or radio. The states could be: Success state Error state Warning state Loading state
         */
        "state"?: FormCheckState;
        /**
          * Set whether is a checkbox input or a radio input
         */
        "type": FormCheckType;
        /**
          * A string representing the value of the checkbox or radio
         */
        "value"?: string;
    }
    interface MFormSwitch {
        /**
          * Flag to change the check state
         */
        "isChecked"?: boolean;
        /**
          * Flag to disable the input
         */
        "isDisabled": boolean;
        /**
          * The text to display in the switch.
         */
        "label": string;
        /**
          * The text to display when the switch is off.
         */
        "labelOff": string;
        /**
          * The text to display when the switch is on.
         */
        "labelOn": string;
        /**
          * Id
         */
        "mId": string;
    }
    interface MHint {
        /**
          * Right icon for the hint
         */
        "iconEnd"?: string;
        /**
          * Right icon family class
         */
        "iconEndFamilyClass"?: string;
        /**
          * Right icon family class
         */
        "iconEndFamilyPrefix"?: string;
        /**
          * Size for the icons
         */
        "iconSize": string;
        /**
          * Left icon for the hint
         */
        "iconStart"?: string;
        /**
          * Left icon family class
         */
        "iconStartFamilyClass"?: string;
        /**
          * Left icon family class
         */
        "iconStartFamilyPrefix"?: string;
        /**
          * Hint text
         */
        "text": string;
        /**
          * Theme for the hint
         */
        "theme"?: string;
    }
    interface MIcon {
        /**
          * To set background color
         */
        "backgroundColor"?: string;
        /**
          * To set css color
         */
        "color"?: string;
        /**
          * Loading animation duration
         */
        "duration": number;
        /**
          * Family class
         */
        "familyClass": string;
        /**
          * Family prefix
         */
        "familyPrefix": string;
        /**
          * Name of icon to use (in kebab-case)
         */
        "icon": string;
        /**
          * Is loading
         */
        "isLoading": boolean;
        /**
          * Font size of the icon
         */
        "size"?: string;
        /**
          * Theme of the icon
         */
        "theme"?: string;
    }
    interface MInput {
        /**
          * Hint to display, also used to display validity feedback
         */
        "hint"?: string;
        /**
          * Icon to display on hint right
         */
        "hintIconEnd"?: string;
        /**
          * Hint right icon family class
         */
        "hintIconEndFamilyClass"?: string;
        /**
          * Hint right icon family class
         */
        "hintIconEndFamilyPrefix"?: string;
        /**
          * Icon to display on hint left
         */
        "hintIconStart"?: string;
        /**
          * Hint left icon family class
         */
        "hintIconStartFamilyClass"?: string;
        /**
          * Hint left icon family class
         */
        "hintIconStartFamilyPrefix"?: string;
        /**
          * Icon to display on input right
         */
        "iconEnd"?: string;
        /**
          * Right icon family class
         */
        "iconEndFamilyClass"?: string;
        /**
          * Right icon family class
         */
        "iconEndFamilyPrefix"?: string;
        /**
          * Icon to display on input left
         */
        "iconStart"?: string;
        /**
          * Left icon family class
         */
        "iconStartFamilyClass"?: string;
        /**
          * Left icon family class
         */
        "iconStartFamilyPrefix"?: string;
        /**
          * Flag to disable the input
         */
        "isDisabled": boolean;
        /**
          * Add is-invalid class
         */
        "isInvalid": boolean;
        /**
          * Flag for loading state.
         */
        "isLoading": boolean;
        /**
          * The label text
         */
        "label": string;
        /**
          * Icon for the label text
         */
        "labelIcon": string;
        /**
          * Icon label family class
         */
        "labelIconFamilyClass"?: string;
        /**
          * Icon label family class
         */
        "labelIconFamilyPrefix"?: string;
        /**
          * Change the layout direction to put the label on top or left of input
         */
        "layoutDirection": FormControlLayoutDirection;
        /**
          * The id of the input
         */
        "mId": string;
        /**
          * The name of the input
         */
        "name"?: string;
        /**
          * The placeholder text
         */
        "placeholder": string;
        /**
          * The type of the input
         */
        "type": string;
        /**
          * The value of the input
         */
        "value": string | number;
    }
    interface MListItem {
        /**
          * Alternative value
         */
        "alternativeValue"?: string | number;
        /**
          * Class for button custom action
         */
        "customActionClass"?: string;
        /**
          * End custom icon
         */
        "customActionEndIcon"?: string;
        /**
          * Family class for custom action icon
         */
        "customActionEndIconFamilyClass"?: string;
        /**
          * Family prefix for custom action icon
         */
        "customActionEndIconFamilyPrefix"?: string;
        /**
          * The icon to display
         */
        "icon"?: string;
        /**
          * Icon family class
         */
        "iconFamilyClass"?: string;
        /**
          * Icon family class
         */
        "iconFamilyPrefix"?: string;
        /**
          * Url to replace the default icon image
         */
        "image": string | null;
        /**
          * Right custom icon clickable
         */
        "isLoading"?: boolean;
        /**
          * Has borders rounded
         */
        "isPill": boolean;
        /**
          * Props for the list item navegable variant
         */
        "navegableProps"?: NavegableProps;
        /**
          * Props for the list item selectable variant
         */
        "selectableProps"?: SelectableProps;
        /**
          * Subtext of the list.
         */
        "subtext": string;
        /**
          * Main text of the list.
         */
        "text": string;
        /**
          * The theme to use.
         */
        "theme"?: string;
        /**
          * Theme to apply in the list value
         */
        "themeValue"?: string;
        /**
          * Value of the list
         */
        "value"?: string | number;
        /**
          * Variant for text item list or complete item list
         */
        "variant"?: ListItemVariant;
    }
    interface MModal {
        /**
          * Close button text
         */
        "closeText"?: string;
        /**
          * Minimum size to apply the fullscreen
         */
        "fullScreenFrom"?: FullScreenFrom;
        /**
          * Background image header
         */
        "imageHeader"?: string;
        /**
          * Is modal centered
         */
        "isCentered"?: boolean;
        /**
          * Is fullscreen in all sizes
         */
        "isFullScreen"?: boolean;
        /**
          * Is modal scrollable
         */
        "isScrollable"?: boolean;
        /**
          * Is backdrop static
         */
        "isStatic"?: boolean;
        /**
          * Modal size
         */
        "modalSize"?: ModalSize;
        /**
          * the name of the modal
         */
        "name": string;
        /**
          * No display close button
         */
        "showCloseButton"?: boolean;
    }
    interface MOffcanvas {
        /**
          * Close button text
         */
        "closeText"?: string;
        /**
          * Is body scrollable while offcanvas is active
         */
        "isScrollable"?: boolean;
        /**
          * Is backdrop static
         */
        "isStatic"?: boolean;
        /**
          * the name of the offcanvas
         */
        "name": string;
        /**
          * Position to show offcanvas from
         */
        "openFrom": PositionToggleFrom;
        /**
          * No display close button
         */
        "showCloseButton"?: boolean;
    }
    interface MProgressBar {
        /**
          * Additional classes for progress bar
         */
        "classNameBar"?: string;
        /**
          * Additional classes for component container
         */
        "classNameContainer"?: string;
        /**
          * Additional classes for progress container
         */
        "classNameProgress"?: string;
        /**
          * Current progress-bar value
         */
        "currentValue": number;
        /**
          * Enable dark mode
         */
        "enableDarkMode": boolean;
        /**
          * Enable striped animation
         */
        "enableStripedAnimation": boolean;
        /**
          * Maximum value of the bar
         */
        "maxValue": number;
        /**
          * Minimum value of the bar
         */
        "minValue": number;
    }
    interface MQuickAction {
        /**
          * The action icon for the quick action
         */
        "actionIcon"?: string;
        /**
          * The action word for the quick action
         */
        "actionWord"?: string;
        /**
          * The extra info of the quick action
         */
        "extraInfo"?: string;
        /**
          * The icon of the quick action
         */
        "icon"?: string;
        /**
          * Icon family class
         */
        "iconFamilyClass"?: string;
        /**
          * Icon family class
         */
        "iconFamilyPrefix"?: string;
        /**
          * The image of the quick action
         */
        "image"?: string;
        /**
          * The state of the quick action
         */
        "state"?: QuickActionState;
        /**
          * The subtext of the quick action
         */
        "subtext"?: string;
        /**
          * The main text of the quick action
         */
        "text": string;
        /**
          * The variant of the quick action
         */
        "variant"?: QuickActionVariant;
    }
    interface MSearch {
        /**
          * Hint to display, also used to display validity feedback
         */
        "hint"?: string;
        /**
          * Icon to display on hint right
         */
        "hintIconEnd"?: string;
        /**
          * Hint right icon family class
         */
        "hintIconEndFamilyClass"?: string;
        /**
          * Hint right icon family class
         */
        "hintIconEndFamilyPrefix"?: string;
        /**
          * Icon to display on hint left
         */
        "hintIconStart"?: string;
        /**
          * Hint left icon family class
         */
        "hintIconStartFamilyClass"?: string;
        /**
          * Hint left icon family class
         */
        "hintIconStartFamilyPrefix"?: string;
        /**
          * Icon to display on input right
         */
        "iconEnd"?: string;
        /**
          * Right icon family class
         */
        "iconEndFamilyClass"?: string;
        /**
          * Right icon family class
         */
        "iconEndFamilyPrefix"?: string;
        /**
          * Flag to disable the input
         */
        "isDisabled": boolean;
        /**
          * Flag for loading state.
         */
        "isLoading": boolean;
        /**
          * Flag to read only the input
         */
        "isReadOnly": boolean;
        /**
          * The label text
         */
        "label": string;
        /**
          * Icon to display on label right
         */
        "labelIcon"?: string;
        /**
          * Icon label family class
         */
        "labelIconFamilyClass"?: string;
        /**
          * Icon label family class
         */
        "labelIconFamilyPrefix"?: string;
        /**
          * Change the layout direction to put the label on top or left of input
         */
        "layoutDirection": FormControlLayoutDirection;
        /**
          * The id of the input
         */
        "mId": string;
        /**
          * The placeholder text
         */
        "placeholder": string;
        /**
          * Theme to use for the search
         */
        "theme"?: string;
        /**
          * The type of the input
         */
        "type": string;
        /**
          * The value of the input
         */
        "value": string;
        /**
          * Variant to use for the search
         */
        "variant"?: string;
    }
    interface MSegmentControl {
        /**
          * Aria label to describe the segment control
         */
        "description"?: string;
    }
    interface MSegmentControlItem {
        /**
          * Is checked
         */
        "isChecked"?: boolean;
        /**
          * Is disabled
         */
        "isDisabled"?: boolean;
        /**
          * Label of the radio
         */
        "label": string;
        /**
          * Id of the radio
         */
        "mId": string;
        /**
          * Name of the radio
         */
        "name": string;
        /**
          * State of the input
         */
        "state"?: InputState;
        /**
          * Value of the radio
         */
        "value": string;
    }
    interface MSelect {
        /**
          * The hint of the select in full variant
         */
        "hint"?: string;
        /**
          * The hint icon for the select in full variant
         */
        "hintIconEnd"?: string;
        /**
          * Hint right icon family class
         */
        "hintIconEndFamilyClass"?: string;
        /**
          * Hint right icon family class
         */
        "hintIconEndFamilyPrefix"?: string;
        /**
          * The hint icon for the select in full variant
         */
        "hintIconStart"?: string;
        /**
          * Hint left icon family class
         */
        "hintIconStartFamilyClass"?: string;
        /**
          * Hint left icon family class
         */
        "hintIconStartFamilyPrefix"?: string;
        /**
          * The end icon for the select
         */
        "iconEnd"?: string;
        /**
          * Right icon family class
         */
        "iconEndFamilyClass"?: string;
        /**
          * Right icon family class
         */
        "iconEndFamilyPrefix"?: string;
        /**
          * The middle icon for the select
         */
        "iconMiddle"?: string;
        /**
          * Middle icon family class
         */
        "iconMiddleFamilyClass"?: string;
        /**
          * Middle icon family class
         */
        "iconMiddleFamilyPrefix"?: string;
        /**
          * The start icon for the select
         */
        "iconStart"?: string;
        /**
          * Left icon family class
         */
        "iconStartFamilyClass"?: string;
        /**
          * Left icon family class
         */
        "iconStartFamilyPrefix"?: string;
        /**
          * The select is disabled
         */
        "isDisabled": boolean;
        /**
          * Flag for loading state.
         */
        "isLoading": boolean;
        /**
          * The label of the select in full variant
         */
        "label"?: string;
        /**
          * Callback to extract the label from the option
         */
        "labelExtractor": (item: any) => string;
        /**
          * Icon for the label text
         */
        "labelIcon": string;
        /**
          * Icon label family class
         */
        "labelIconFamilyClass"?: string;
        /**
          * Icon label family class
         */
        "labelIconFamilyPrefix"?: string;
        /**
          * Change the layout direction to put the label on top or left of select
         */
        "layoutDirection": FormControlLayoutDirection;
        /**
          * Id of the select
         */
        "mId": string;
        /**
          * The name of the input
         */
        "name"?: string;
        /**
          * The select options
         */
        "options": Array<Record<string, unknown>>;
        /**
          * The value selected of the component
         */
        "selectedOption"?: Record<string, unknown>;
        /**
          * The theme of the select
         */
        "theme"?: string;
        /**
          * Callback to extract the value from the option
         */
        "valueExtractor": (item: any) => string | number;
        /**
          * The variant of the select
         */
        "variant"?: SelectLayoutVariant;
    }
    interface MShortcutToggle {
        /**
          * Shortcut icon
         */
        "icon"?: string;
        /**
          * Icon family class
         */
        "iconFamilyClass"?: string;
        /**
          * Icon family class
         */
        "iconFamilyPrefix"?: string;
        /**
          * Is checked
         */
        "isChecked"?: boolean;
        /**
          * Shortcut label
         */
        "label"?: string;
        /**
          * Id of the input
         */
        "mId": string;
        /**
          * Name of the input
         */
        "name": string;
        /**
          * Input and shortcut state
         */
        "state"?: InputState;
        /**
          * Shortcut text
         */
        "subtext"?: string;
        /**
          * Shortcut text
         */
        "text"?: string;
        /**
          * Input value
         */
        "value": string;
        /**
          * Theme
         */
        "white": boolean;
    }
}
export interface MAlertCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMAlertElement;
}
export interface MButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMButtonElement;
}
export interface MCounterCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMCounterElement;
}
export interface MCouponCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMCouponElement;
}
export interface MCurrencyCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMCurrencyElement;
}
export interface MFormCheckCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMFormCheckElement;
}
export interface MFormSwitchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMFormSwitchElement;
}
export interface MInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMInputElement;
}
export interface MListItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMListItemElement;
}
export interface MModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMModalElement;
}
export interface MOffcanvasCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMOffcanvasElement;
}
export interface MQuickActionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMQuickActionElement;
}
export interface MSearchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMSearchElement;
}
export interface MSegmentControlItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMSegmentControlItemElement;
}
export interface MSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMSelectElement;
}
export interface MShortcutToggleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMShortcutToggleElement;
}
declare global {
    interface HTMLMAlertElement extends Components.MAlert, HTMLStencilElement {
    }
    var HTMLMAlertElement: {
        prototype: HTMLMAlertElement;
        new (): HTMLMAlertElement;
    };
    interface HTMLMAppElement extends Components.MApp, HTMLStencilElement {
    }
    var HTMLMAppElement: {
        prototype: HTMLMAppElement;
        new (): HTMLMAppElement;
    };
    interface HTMLMBadgeElement extends Components.MBadge, HTMLStencilElement {
    }
    var HTMLMBadgeElement: {
        prototype: HTMLMBadgeElement;
        new (): HTMLMBadgeElement;
    };
    interface HTMLMButtonElement extends Components.MButton, HTMLStencilElement {
    }
    var HTMLMButtonElement: {
        prototype: HTMLMButtonElement;
        new (): HTMLMButtonElement;
    };
    interface HTMLMCounterElement extends Components.MCounter, HTMLStencilElement {
    }
    var HTMLMCounterElement: {
        prototype: HTMLMCounterElement;
        new (): HTMLMCounterElement;
    };
    interface HTMLMCouponElement extends Components.MCoupon, HTMLStencilElement {
    }
    var HTMLMCouponElement: {
        prototype: HTMLMCouponElement;
        new (): HTMLMCouponElement;
    };
    interface HTMLMCurrencyElement extends Components.MCurrency, HTMLStencilElement {
    }
    var HTMLMCurrencyElement: {
        prototype: HTMLMCurrencyElement;
        new (): HTMLMCurrencyElement;
    };
    interface HTMLMFormCheckElement extends Components.MFormCheck, HTMLStencilElement {
    }
    var HTMLMFormCheckElement: {
        prototype: HTMLMFormCheckElement;
        new (): HTMLMFormCheckElement;
    };
    interface HTMLMFormSwitchElement extends Components.MFormSwitch, HTMLStencilElement {
    }
    var HTMLMFormSwitchElement: {
        prototype: HTMLMFormSwitchElement;
        new (): HTMLMFormSwitchElement;
    };
    interface HTMLMHintElement extends Components.MHint, HTMLStencilElement {
    }
    var HTMLMHintElement: {
        prototype: HTMLMHintElement;
        new (): HTMLMHintElement;
    };
    interface HTMLMIconElement extends Components.MIcon, HTMLStencilElement {
    }
    var HTMLMIconElement: {
        prototype: HTMLMIconElement;
        new (): HTMLMIconElement;
    };
    interface HTMLMInputElement extends Components.MInput, HTMLStencilElement {
    }
    var HTMLMInputElement: {
        prototype: HTMLMInputElement;
        new (): HTMLMInputElement;
    };
    interface HTMLMListItemElement extends Components.MListItem, HTMLStencilElement {
    }
    var HTMLMListItemElement: {
        prototype: HTMLMListItemElement;
        new (): HTMLMListItemElement;
    };
    interface HTMLMModalElement extends Components.MModal, HTMLStencilElement {
    }
    var HTMLMModalElement: {
        prototype: HTMLMModalElement;
        new (): HTMLMModalElement;
    };
    interface HTMLMOffcanvasElement extends Components.MOffcanvas, HTMLStencilElement {
    }
    var HTMLMOffcanvasElement: {
        prototype: HTMLMOffcanvasElement;
        new (): HTMLMOffcanvasElement;
    };
    interface HTMLMProgressBarElement extends Components.MProgressBar, HTMLStencilElement {
    }
    var HTMLMProgressBarElement: {
        prototype: HTMLMProgressBarElement;
        new (): HTMLMProgressBarElement;
    };
    interface HTMLMQuickActionElement extends Components.MQuickAction, HTMLStencilElement {
    }
    var HTMLMQuickActionElement: {
        prototype: HTMLMQuickActionElement;
        new (): HTMLMQuickActionElement;
    };
    interface HTMLMSearchElement extends Components.MSearch, HTMLStencilElement {
    }
    var HTMLMSearchElement: {
        prototype: HTMLMSearchElement;
        new (): HTMLMSearchElement;
    };
    interface HTMLMSegmentControlElement extends Components.MSegmentControl, HTMLStencilElement {
    }
    var HTMLMSegmentControlElement: {
        prototype: HTMLMSegmentControlElement;
        new (): HTMLMSegmentControlElement;
    };
    interface HTMLMSegmentControlItemElement extends Components.MSegmentControlItem, HTMLStencilElement {
    }
    var HTMLMSegmentControlItemElement: {
        prototype: HTMLMSegmentControlItemElement;
        new (): HTMLMSegmentControlItemElement;
    };
    interface HTMLMSelectElement extends Components.MSelect, HTMLStencilElement {
    }
    var HTMLMSelectElement: {
        prototype: HTMLMSelectElement;
        new (): HTMLMSelectElement;
    };
    interface HTMLMShortcutToggleElement extends Components.MShortcutToggle, HTMLStencilElement {
    }
    var HTMLMShortcutToggleElement: {
        prototype: HTMLMShortcutToggleElement;
        new (): HTMLMShortcutToggleElement;
    };
    interface HTMLElementTagNameMap {
        "m-alert": HTMLMAlertElement;
        "m-app": HTMLMAppElement;
        "m-badge": HTMLMBadgeElement;
        "m-button": HTMLMButtonElement;
        "m-counter": HTMLMCounterElement;
        "m-coupon": HTMLMCouponElement;
        "m-currency": HTMLMCurrencyElement;
        "m-form-check": HTMLMFormCheckElement;
        "m-form-switch": HTMLMFormSwitchElement;
        "m-hint": HTMLMHintElement;
        "m-icon": HTMLMIconElement;
        "m-input": HTMLMInputElement;
        "m-list-item": HTMLMListItemElement;
        "m-modal": HTMLMModalElement;
        "m-offcanvas": HTMLMOffcanvasElement;
        "m-progress-bar": HTMLMProgressBarElement;
        "m-quick-action": HTMLMQuickActionElement;
        "m-search": HTMLMSearchElement;
        "m-segment-control": HTMLMSegmentControlElement;
        "m-segment-control-item": HTMLMSegmentControlItemElement;
        "m-select": HTMLMSelectElement;
        "m-shortcut-toggle": HTMLMShortcutToggleElement;
    }
}
declare namespace LocalJSX {
    interface MAlert {
        /**
          * Emitted when the button has been clicked.
         */
        "onMClose"?: (event: MAlertCustomEvent<any>) => void;
        /**
          * Show close button
         */
        "showClose"?: boolean;
        /**
          * Show icon theme in the alert
         */
        "showIcon"?: boolean;
        /**
          * Theme for the alert
         */
        "theme"?: string;
    }
    interface MApp {
        /**
          * Icon settings
         */
        "iconSettings"?: IconSettings;
    }
    interface MBadge {
        /**
          * The text of badge
         */
        "text"?: string;
        /**
          * The theme to use.
         */
        "theme"?: string;
    }
    interface MButton {
        /**
          * Icon right to display
         */
        "iconEnd"?: string;
        /**
          * Icon right family class
         */
        "iconEndFamilyClass"?: string;
        /**
          * Icon right family prefix
         */
        "iconEndFamilyPrefix"?: string;
        /**
          * Icon left to display
         */
        "iconStart"?: string;
        /**
          * Icon left family class
         */
        "iconStartFamilyClass"?: string;
        /**
          * Icon left family prefix
         */
        "iconStartFamilyPrefix"?: string;
        /**
          * Flag for loading state and disable button.
         */
        "isLoading"?: boolean;
        /**
          * Flag to switch to pill button border radius.
         */
        "isPill"?: boolean;
        /**
          * Emitted when the button has been clicked.
         */
        "onMClick"?: (event: MButtonCustomEvent<any>) => void;
        /**
          * Flag to set the button as active.
         */
        "state"?: InputState;
        /**
          * The text to display.
         */
        "text"?: string;
        /**
          * The theme to use.
         */
        "theme"?: string;
        /**
          * The type of the button.
         */
        "type"?: ButtonType;
        /**
          * The value of the button.
         */
        "value"?: string;
        /**
          * The variant to use.
         */
        "variant"?: ButtonVariant;
    }
    interface MCounter {
        /**
          * Hint text
         */
        "hint"?: string;
        /**
          * Right icon of the hint text
         */
        "hintIconEnd"?: string;
        /**
          * Hint right icon family class
         */
        "hintIconEndFamilyClass"?: string;
        /**
          * Hint right icon family class
         */
        "hintIconEndFamilyPrefix"?: string;
        /**
          * Left icon of the hint text
         */
        "hintIconStart"?: string;
        /**
          * Hint left icon family class
         */
        "hintIconStartFamilyClass"?: string;
        /**
          * Hint left icon family class
         */
        "hintIconStartFamilyPrefix"?: string;
        /**
          * Is disabled counter
         */
        "isDisabled"?: boolean;
        /**
          * Flag for loading state.
         */
        "isLoading"?: boolean;
        /**
          * Label of the input
         */
        "label"?: string;
        /**
          * Icon for the label text
         */
        "labelIcon"?: string;
        /**
          * Icon label family class
         */
        "labelIconFamilyClass"?: string;
        /**
          * Icon label family class
         */
        "labelIconFamilyPrefix"?: string;
        /**
          * Change the layout direction to put the label on top or left of input
         */
        "layoutDirection"?: FormControlLayoutDirection;
        /**
          * Id of the input
         */
        "mId": string;
        /**
          * Maximum value for the input
         */
        "maxValue": number;
        /**
          * Minimum value for the input
         */
        "minValue": number;
        /**
          * Event for button pressed
         */
        "onMClick"?: (event: MCounterCustomEvent<any>) => void;
        /**
          * Event for input change
         */
        "onMInput"?: (event: MCounterCustomEvent<any>) => void;
        /**
          * Theme of the counter
         */
        "theme"?: string;
        /**
          * Value of the input
         */
        "value": number;
        /**
          * Variant of the counter
         */
        "variant"?: 'default' | 'prime';
    }
    interface MCoupon {
        /**
          * Text for the coupon button
         */
        "buttonText"?: string;
        /**
          * Has a select input
         */
        "hasSelect"?: boolean;
        /**
          * Hint for the m-coupon
         */
        "hint"?: string;
        /**
          * Icon end for the hint text
         */
        "hintIconEnd"?: string;
        /**
          * Hint right icon family class
         */
        "hintIconEndFamilyClass"?: string;
        /**
          * Hint right icon family class
         */
        "hintIconEndFamilyPrefix"?: string;
        /**
          * Icon start for the hint text
         */
        "hintIconStart"?: string;
        /**
          * Hint left icon family class
         */
        "hintIconStartFamilyClass"?: string;
        /**
          * Hint left icon family class
         */
        "hintIconStartFamilyPrefix"?: string;
        /**
          * Icon of the end
         */
        "iconEnd"?: string;
        /**
          * Right icon family class
         */
        "iconEndFamilyClass"?: string;
        /**
          * Right icon family class
         */
        "iconEndFamilyPrefix"?: string;
        /**
          * Icon of the middle
         */
        "iconMiddle"?: string;
        /**
          * Middle icon family class
         */
        "iconMiddleFamilyClass"?: string;
        /**
          * Middle icon family class
         */
        "iconMiddleFamilyPrefix"?: string;
        /**
          * Icon of the left
         */
        "iconStart"?: string;
        /**
          * Left icon family class
         */
        "iconStartFamilyClass"?: string;
        /**
          * Left icon family class
         */
        "iconStartFamilyPrefix"?: string;
        /**
          * Flag for loading state.
         */
        "isLoading"?: boolean;
        /**
          * Label for the input
         */
        "label"?: string;
        /**
          * Icon for the label text
         */
        "labelIcon"?: string;
        /**
          * Icon label family class
         */
        "labelIconFamilyClass"?: string;
        /**
          * Icon label family class
         */
        "labelIconFamilyPrefix"?: string;
        /**
          * Change the layout direction to put the label on top or left of input
         */
        "layoutDirection"?: FormControlLayoutDirection;
        /**
          * Id for the input
         */
        "mId": string;
        /**
          * Emitted when the button is clicked
         */
        "onMClick"?: (event: MCouponCustomEvent<CouponEvent>) => void;
        /**
          * Placeholder for the input
         */
        "placeholder"?: string;
        /**
          * Theme for the m-cupon
         */
        "theme"?: string;
        /**
          * * The type of the input
         */
        "type"?: CouponInputType;
    }
    interface MCurrency {
        /**
          * Options for the m-currency
         */
        "currencyOptions": Options;
        /**
          * Hint text for the m-currency
         */
        "hint"?: string;
        /**
          * Icon end for the hint text
         */
        "hintIconEnd"?: string;
        /**
          * Hint right icon family class
         */
        "hintIconEndFamilyClass"?: string;
        /**
          * Hint right icon family class
         */
        "hintIconEndFamilyPrefix"?: string;
        /**
          * Icon start for the hint text
         */
        "hintIconStart"?: string;
        /**
          * Hint left icon family class
         */
        "hintIconStartFamilyClass"?: string;
        /**
          * Hint left icon family class
         */
        "hintIconStartFamilyPrefix"?: string;
        /**
          * Icon for the end
         */
        "iconEnd"?: string;
        /**
          * Right icon family class
         */
        "iconEndFamilyClass"?: string;
        /**
          * Right icon family class
         */
        "iconEndFamilyPrefix"?: string;
        /**
          * Icon for the middle
         */
        "iconMiddle"?: string;
        /**
          * Middle icon family class
         */
        "iconMiddleFamilyClass"?: string;
        /**
          * Middle icon family class
         */
        "iconMiddleFamilyPrefix"?: string;
        /**
          * Icon for the left
         */
        "iconStart"?: string;
        /**
          * Left icon family class
         */
        "iconStartFamilyClass"?: string;
        /**
          * Left icon family class
         */
        "iconStartFamilyPrefix"?: string;
        /**
          * The input is disabled
         */
        "isDisabled"?: boolean;
        /**
          * Flag for loading state.
         */
        "isLoading"?: boolean;
        /**
          * Label for the input
         */
        "label"?: string;
        /**
          * Callback to extract the label from the option
         */
        "labelExtractor"?: (item: any) => string;
        /**
          * Icon for the label text
         */
        "labelIcon"?: string;
        /**
          * Icon label family class
         */
        "labelIconFamilyClass"?: string;
        /**
          * Icon label family class
         */
        "labelIconFamilyPrefix"?: string;
        /**
          * Change the layout direction to put the label on top or left of input
         */
        "layoutDirection"?: FormControlLayoutDirection;
        /**
          * Id for the input
         */
        "mId": string;
        /**
          * * The max value of the input
         */
        "maxValue"?: number;
        /**
          * * The min value of the input
         */
        "minValue"?: number;
        /**
          * Emitted when the inputs change
         */
        "onMChange"?: (event: MCurrencyCustomEvent<CurrencyEvent>) => void;
        /**
          * Placeholder for the input
         */
        "placeholder"?: string;
        /**
          * Select options
         */
        "selectOptions"?: Array<any>;
        /**
          * Theme for the m-currency
         */
        "theme"?: string;
        /**
          * * The value of the input
         */
        "value"?: number;
        /**
          * Callback to extract the value from the option
         */
        "valueExtractor"?: (item: any) => string | number;
        /**
          * Variant for the m-currency
         */
        "variant"?: CurrencyVariant;
    }
    interface MFormCheck {
        /**
          * Set checkbox as toggle button
         */
        "isButton"?: boolean;
        /**
          * Set checkbox or radio button marked as selected or not
         */
        "isChecked"?: boolean;
        /**
          * Set input as disabled
         */
        "isDisabled"?: boolean;
        /**
          * Set view of checkbox as indeterminated
         */
        "isIndeterminate"?: boolean;
        /**
          * Text that will be displayed beside Check input or Radio input
         */
        "label"?: string;
        /**
          * Form control identifier
         */
        "mId": string;
        /**
          * HTML Name to use within a form or JS reference
         */
        "name"?: string;
        /**
          * Emitted when the switch has changed
         */
        "onMChange"?: (event: MFormCheckCustomEvent<any>) => void;
        /**
          * State of checkbox or radio. The states could be: Success state Error state Warning state Loading state
         */
        "state"?: FormCheckState;
        /**
          * Set whether is a checkbox input or a radio input
         */
        "type": FormCheckType;
        /**
          * A string representing the value of the checkbox or radio
         */
        "value"?: string;
    }
    interface MFormSwitch {
        /**
          * Flag to change the check state
         */
        "isChecked"?: boolean;
        /**
          * Flag to disable the input
         */
        "isDisabled"?: boolean;
        /**
          * The text to display in the switch.
         */
        "label": string;
        /**
          * The text to display when the switch is off.
         */
        "labelOff"?: string;
        /**
          * The text to display when the switch is on.
         */
        "labelOn"?: string;
        /**
          * Id
         */
        "mId": string;
        /**
          * Emitted when the switch has changed
         */
        "onMChange"?: (event: MFormSwitchCustomEvent<boolean>) => void;
    }
    interface MHint {
        /**
          * Right icon for the hint
         */
        "iconEnd"?: string;
        /**
          * Right icon family class
         */
        "iconEndFamilyClass"?: string;
        /**
          * Right icon family class
         */
        "iconEndFamilyPrefix"?: string;
        /**
          * Size for the icons
         */
        "iconSize"?: string;
        /**
          * Left icon for the hint
         */
        "iconStart"?: string;
        /**
          * Left icon family class
         */
        "iconStartFamilyClass"?: string;
        /**
          * Left icon family class
         */
        "iconStartFamilyPrefix"?: string;
        /**
          * Hint text
         */
        "text": string;
        /**
          * Theme for the hint
         */
        "theme"?: string;
    }
    interface MIcon {
        /**
          * To set background color
         */
        "backgroundColor"?: string;
        /**
          * To set css color
         */
        "color"?: string;
        /**
          * Loading animation duration
         */
        "duration"?: number;
        /**
          * Family class
         */
        "familyClass"?: string;
        /**
          * Family prefix
         */
        "familyPrefix"?: string;
        /**
          * Name of icon to use (in kebab-case)
         */
        "icon": string;
        /**
          * Is loading
         */
        "isLoading"?: boolean;
        /**
          * Font size of the icon
         */
        "size"?: string;
        /**
          * Theme of the icon
         */
        "theme"?: string;
    }
    interface MInput {
        /**
          * Hint to display, also used to display validity feedback
         */
        "hint"?: string;
        /**
          * Icon to display on hint right
         */
        "hintIconEnd"?: string;
        /**
          * Hint right icon family class
         */
        "hintIconEndFamilyClass"?: string;
        /**
          * Hint right icon family class
         */
        "hintIconEndFamilyPrefix"?: string;
        /**
          * Icon to display on hint left
         */
        "hintIconStart"?: string;
        /**
          * Hint left icon family class
         */
        "hintIconStartFamilyClass"?: string;
        /**
          * Hint left icon family class
         */
        "hintIconStartFamilyPrefix"?: string;
        /**
          * Icon to display on input right
         */
        "iconEnd"?: string;
        /**
          * Right icon family class
         */
        "iconEndFamilyClass"?: string;
        /**
          * Right icon family class
         */
        "iconEndFamilyPrefix"?: string;
        /**
          * Icon to display on input left
         */
        "iconStart"?: string;
        /**
          * Left icon family class
         */
        "iconStartFamilyClass"?: string;
        /**
          * Left icon family class
         */
        "iconStartFamilyPrefix"?: string;
        /**
          * Flag to disable the input
         */
        "isDisabled"?: boolean;
        /**
          * Add is-invalid class
         */
        "isInvalid"?: boolean;
        /**
          * Flag for loading state.
         */
        "isLoading"?: boolean;
        /**
          * The label text
         */
        "label"?: string;
        /**
          * Icon for the label text
         */
        "labelIcon"?: string;
        /**
          * Icon label family class
         */
        "labelIconFamilyClass"?: string;
        /**
          * Icon label family class
         */
        "labelIconFamilyPrefix"?: string;
        /**
          * Change the layout direction to put the label on top or left of input
         */
        "layoutDirection"?: FormControlLayoutDirection;
        /**
          * The id of the input
         */
        "mId": string;
        /**
          * The name of the input
         */
        "name"?: string;
        /**
          * Emitted when blur the input
         */
        "onMBlur"?: (event: MInputCustomEvent<any>) => void;
        /**
          * Emitted when the input value has changed
         */
        "onMChange"?: (event: MInputCustomEvent<string | number>) => void;
        /**
          * The placeholder text
         */
        "placeholder"?: string;
        /**
          * The type of the input
         */
        "type"?: string;
        /**
          * The value of the input
         */
        "value"?: string | number;
    }
    interface MListItem {
        /**
          * Alternative value
         */
        "alternativeValue"?: string | number;
        /**
          * Class for button custom action
         */
        "customActionClass"?: string;
        /**
          * End custom icon
         */
        "customActionEndIcon"?: string;
        /**
          * Family class for custom action icon
         */
        "customActionEndIconFamilyClass"?: string;
        /**
          * Family prefix for custom action icon
         */
        "customActionEndIconFamilyPrefix"?: string;
        /**
          * The icon to display
         */
        "icon"?: string;
        /**
          * Icon family class
         */
        "iconFamilyClass"?: string;
        /**
          * Icon family class
         */
        "iconFamilyPrefix"?: string;
        /**
          * Url to replace the default icon image
         */
        "image"?: string | null;
        /**
          * Right custom icon clickable
         */
        "isLoading"?: boolean;
        /**
          * Has borders rounded
         */
        "isPill"?: boolean;
        /**
          * Props for the list item navegable variant
         */
        "navegableProps"?: NavegableProps;
        /**
          * Emitted when the right custom icon has been clicked.
         */
        "onMCustomClick"?: (event: MListItemCustomEvent<any>) => void;
        /**
          * Props for the list item selectable variant
         */
        "selectableProps"?: SelectableProps;
        /**
          * Subtext of the list.
         */
        "subtext"?: string;
        /**
          * Main text of the list.
         */
        "text"?: string;
        /**
          * The theme to use.
         */
        "theme"?: string;
        /**
          * Theme to apply in the list value
         */
        "themeValue"?: string;
        /**
          * Value of the list
         */
        "value"?: string | number;
        /**
          * Variant for text item list or complete item list
         */
        "variant"?: ListItemVariant;
    }
    interface MModal {
        /**
          * Close button text
         */
        "closeText"?: string;
        /**
          * Minimum size to apply the fullscreen
         */
        "fullScreenFrom"?: FullScreenFrom;
        /**
          * Background image header
         */
        "imageHeader"?: string;
        /**
          * Is modal centered
         */
        "isCentered"?: boolean;
        /**
          * Is fullscreen in all sizes
         */
        "isFullScreen"?: boolean;
        /**
          * Is modal scrollable
         */
        "isScrollable"?: boolean;
        /**
          * Is backdrop static
         */
        "isStatic"?: boolean;
        /**
          * Modal size
         */
        "modalSize"?: ModalSize;
        /**
          * the name of the modal
         */
        "name": string;
        /**
          * Emitted when the input value has changed
         */
        "onMClose"?: (event: MModalCustomEvent<void>) => void;
        /**
          * No display close button
         */
        "showCloseButton"?: boolean;
    }
    interface MOffcanvas {
        /**
          * Close button text
         */
        "closeText"?: string;
        /**
          * Is body scrollable while offcanvas is active
         */
        "isScrollable"?: boolean;
        /**
          * Is backdrop static
         */
        "isStatic"?: boolean;
        /**
          * the name of the offcanvas
         */
        "name": string;
        /**
          * Emitted when the input value has changed
         */
        "onMClose"?: (event: MOffcanvasCustomEvent<void>) => void;
        /**
          * Position to show offcanvas from
         */
        "openFrom"?: PositionToggleFrom;
        /**
          * No display close button
         */
        "showCloseButton"?: boolean;
    }
    interface MProgressBar {
        /**
          * Additional classes for progress bar
         */
        "classNameBar"?: string;
        /**
          * Additional classes for component container
         */
        "classNameContainer"?: string;
        /**
          * Additional classes for progress container
         */
        "classNameProgress"?: string;
        /**
          * Current progress-bar value
         */
        "currentValue": number;
        /**
          * Enable dark mode
         */
        "enableDarkMode"?: boolean;
        /**
          * Enable striped animation
         */
        "enableStripedAnimation"?: boolean;
        /**
          * Maximum value of the bar
         */
        "maxValue"?: number;
        /**
          * Minimum value of the bar
         */
        "minValue"?: number;
    }
    interface MQuickAction {
        /**
          * The action icon for the quick action
         */
        "actionIcon"?: string;
        /**
          * The action word for the quick action
         */
        "actionWord"?: string;
        /**
          * The extra info of the quick action
         */
        "extraInfo"?: string;
        /**
          * The icon of the quick action
         */
        "icon"?: string;
        /**
          * Icon family class
         */
        "iconFamilyClass"?: string;
        /**
          * Icon family class
         */
        "iconFamilyPrefix"?: string;
        /**
          * The image of the quick action
         */
        "image"?: string;
        /**
          * Emitted when the input value has changed
         */
        "onMClick"?: (event: MQuickActionCustomEvent<any>) => void;
        /**
          * The state of the quick action
         */
        "state"?: QuickActionState;
        /**
          * The subtext of the quick action
         */
        "subtext"?: string;
        /**
          * The main text of the quick action
         */
        "text": string;
        /**
          * The variant of the quick action
         */
        "variant"?: QuickActionVariant;
    }
    interface MSearch {
        /**
          * Hint to display, also used to display validity feedback
         */
        "hint"?: string;
        /**
          * Icon to display on hint right
         */
        "hintIconEnd"?: string;
        /**
          * Hint right icon family class
         */
        "hintIconEndFamilyClass"?: string;
        /**
          * Hint right icon family class
         */
        "hintIconEndFamilyPrefix"?: string;
        /**
          * Icon to display on hint left
         */
        "hintIconStart"?: string;
        /**
          * Hint left icon family class
         */
        "hintIconStartFamilyClass"?: string;
        /**
          * Hint left icon family class
         */
        "hintIconStartFamilyPrefix"?: string;
        /**
          * Icon to display on input right
         */
        "iconEnd"?: string;
        /**
          * Right icon family class
         */
        "iconEndFamilyClass"?: string;
        /**
          * Right icon family class
         */
        "iconEndFamilyPrefix"?: string;
        /**
          * Flag to disable the input
         */
        "isDisabled"?: boolean;
        /**
          * Flag for loading state.
         */
        "isLoading"?: boolean;
        /**
          * Flag to read only the input
         */
        "isReadOnly"?: boolean;
        /**
          * The label text
         */
        "label"?: string;
        /**
          * Icon to display on label right
         */
        "labelIcon"?: string;
        /**
          * Icon label family class
         */
        "labelIconFamilyClass"?: string;
        /**
          * Icon label family class
         */
        "labelIconFamilyPrefix"?: string;
        /**
          * Change the layout direction to put the label on top or left of input
         */
        "layoutDirection"?: FormControlLayoutDirection;
        /**
          * The id of the input
         */
        "mId": string;
        /**
          * Emitted when the input value has changed
         */
        "onMChange"?: (event: MSearchCustomEvent<string>) => void;
        /**
          * Emitted when the button is clicked
         */
        "onMClick"?: (event: MSearchCustomEvent<string>) => void;
        /**
          * The placeholder text
         */
        "placeholder"?: string;
        /**
          * Theme to use for the search
         */
        "theme"?: string;
        /**
          * The type of the input
         */
        "type"?: string;
        /**
          * The value of the input
         */
        "value"?: string;
        /**
          * Variant to use for the search
         */
        "variant"?: string;
    }
    interface MSegmentControl {
        /**
          * Aria label to describe the segment control
         */
        "description"?: string;
    }
    interface MSegmentControlItem {
        /**
          * Is checked
         */
        "isChecked"?: boolean;
        /**
          * Is disabled
         */
        "isDisabled"?: boolean;
        /**
          * Label of the radio
         */
        "label": string;
        /**
          * Id of the radio
         */
        "mId": string;
        /**
          * Name of the radio
         */
        "name": string;
        /**
          * Emitted when the input value has changed
         */
        "onMChange"?: (event: MSegmentControlItemCustomEvent<string>) => void;
        /**
          * State of the input
         */
        "state"?: InputState;
        /**
          * Value of the radio
         */
        "value": string;
    }
    interface MSelect {
        /**
          * The hint of the select in full variant
         */
        "hint"?: string;
        /**
          * The hint icon for the select in full variant
         */
        "hintIconEnd"?: string;
        /**
          * Hint right icon family class
         */
        "hintIconEndFamilyClass"?: string;
        /**
          * Hint right icon family class
         */
        "hintIconEndFamilyPrefix"?: string;
        /**
          * The hint icon for the select in full variant
         */
        "hintIconStart"?: string;
        /**
          * Hint left icon family class
         */
        "hintIconStartFamilyClass"?: string;
        /**
          * Hint left icon family class
         */
        "hintIconStartFamilyPrefix"?: string;
        /**
          * The end icon for the select
         */
        "iconEnd"?: string;
        /**
          * Right icon family class
         */
        "iconEndFamilyClass"?: string;
        /**
          * Right icon family class
         */
        "iconEndFamilyPrefix"?: string;
        /**
          * The middle icon for the select
         */
        "iconMiddle"?: string;
        /**
          * Middle icon family class
         */
        "iconMiddleFamilyClass"?: string;
        /**
          * Middle icon family class
         */
        "iconMiddleFamilyPrefix"?: string;
        /**
          * The start icon for the select
         */
        "iconStart"?: string;
        /**
          * Left icon family class
         */
        "iconStartFamilyClass"?: string;
        /**
          * Left icon family class
         */
        "iconStartFamilyPrefix"?: string;
        /**
          * The select is disabled
         */
        "isDisabled"?: boolean;
        /**
          * Flag for loading state.
         */
        "isLoading"?: boolean;
        /**
          * The label of the select in full variant
         */
        "label"?: string;
        /**
          * Callback to extract the label from the option
         */
        "labelExtractor"?: (item: any) => string;
        /**
          * Icon for the label text
         */
        "labelIcon"?: string;
        /**
          * Icon label family class
         */
        "labelIconFamilyClass"?: string;
        /**
          * Icon label family class
         */
        "labelIconFamilyPrefix"?: string;
        /**
          * Change the layout direction to put the label on top or left of select
         */
        "layoutDirection"?: FormControlLayoutDirection;
        /**
          * Id of the select
         */
        "mId": string;
        /**
          * The name of the input
         */
        "name"?: string;
        /**
          * Emitted when blur the input
         */
        "onMBlur"?: (event: MSelectCustomEvent<any>) => void;
        /**
          * Emitted when the select value has changed
         */
        "onMChange"?: (event: MSelectCustomEvent<any>) => void;
        /**
          * The select options
         */
        "options"?: Array<Record<string, unknown>>;
        /**
          * The value selected of the component
         */
        "selectedOption"?: Record<string, unknown>;
        /**
          * The theme of the select
         */
        "theme"?: string;
        /**
          * Callback to extract the value from the option
         */
        "valueExtractor"?: (item: any) => string | number;
        /**
          * The variant of the select
         */
        "variant"?: SelectLayoutVariant;
    }
    interface MShortcutToggle {
        /**
          * Shortcut icon
         */
        "icon"?: string;
        /**
          * Icon family class
         */
        "iconFamilyClass"?: string;
        /**
          * Icon family class
         */
        "iconFamilyPrefix"?: string;
        /**
          * Is checked
         */
        "isChecked"?: boolean;
        /**
          * Shortcut label
         */
        "label"?: string;
        /**
          * Id of the input
         */
        "mId": string;
        /**
          * Name of the input
         */
        "name": string;
        /**
          * Emitted when the select value has changed
         */
        "onMChange"?: (event: MShortcutToggleCustomEvent<string>) => void;
        /**
          * Input and shortcut state
         */
        "state"?: InputState;
        /**
          * Shortcut text
         */
        "subtext"?: string;
        /**
          * Shortcut text
         */
        "text"?: string;
        /**
          * Input value
         */
        "value": string;
        /**
          * Theme
         */
        "white"?: boolean;
    }
    interface IntrinsicElements {
        "m-alert": MAlert;
        "m-app": MApp;
        "m-badge": MBadge;
        "m-button": MButton;
        "m-counter": MCounter;
        "m-coupon": MCoupon;
        "m-currency": MCurrency;
        "m-form-check": MFormCheck;
        "m-form-switch": MFormSwitch;
        "m-hint": MHint;
        "m-icon": MIcon;
        "m-input": MInput;
        "m-list-item": MListItem;
        "m-modal": MModal;
        "m-offcanvas": MOffcanvas;
        "m-progress-bar": MProgressBar;
        "m-quick-action": MQuickAction;
        "m-search": MSearch;
        "m-segment-control": MSegmentControl;
        "m-segment-control-item": MSegmentControlItem;
        "m-select": MSelect;
        "m-shortcut-toggle": MShortcutToggle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "m-alert": LocalJSX.MAlert & JSXBase.HTMLAttributes<HTMLMAlertElement>;
            "m-app": LocalJSX.MApp & JSXBase.HTMLAttributes<HTMLMAppElement>;
            "m-badge": LocalJSX.MBadge & JSXBase.HTMLAttributes<HTMLMBadgeElement>;
            "m-button": LocalJSX.MButton & JSXBase.HTMLAttributes<HTMLMButtonElement>;
            "m-counter": LocalJSX.MCounter & JSXBase.HTMLAttributes<HTMLMCounterElement>;
            "m-coupon": LocalJSX.MCoupon & JSXBase.HTMLAttributes<HTMLMCouponElement>;
            "m-currency": LocalJSX.MCurrency & JSXBase.HTMLAttributes<HTMLMCurrencyElement>;
            "m-form-check": LocalJSX.MFormCheck & JSXBase.HTMLAttributes<HTMLMFormCheckElement>;
            "m-form-switch": LocalJSX.MFormSwitch & JSXBase.HTMLAttributes<HTMLMFormSwitchElement>;
            "m-hint": LocalJSX.MHint & JSXBase.HTMLAttributes<HTMLMHintElement>;
            "m-icon": LocalJSX.MIcon & JSXBase.HTMLAttributes<HTMLMIconElement>;
            "m-input": LocalJSX.MInput & JSXBase.HTMLAttributes<HTMLMInputElement>;
            "m-list-item": LocalJSX.MListItem & JSXBase.HTMLAttributes<HTMLMListItemElement>;
            "m-modal": LocalJSX.MModal & JSXBase.HTMLAttributes<HTMLMModalElement>;
            "m-offcanvas": LocalJSX.MOffcanvas & JSXBase.HTMLAttributes<HTMLMOffcanvasElement>;
            "m-progress-bar": LocalJSX.MProgressBar & JSXBase.HTMLAttributes<HTMLMProgressBarElement>;
            "m-quick-action": LocalJSX.MQuickAction & JSXBase.HTMLAttributes<HTMLMQuickActionElement>;
            "m-search": LocalJSX.MSearch & JSXBase.HTMLAttributes<HTMLMSearchElement>;
            "m-segment-control": LocalJSX.MSegmentControl & JSXBase.HTMLAttributes<HTMLMSegmentControlElement>;
            "m-segment-control-item": LocalJSX.MSegmentControlItem & JSXBase.HTMLAttributes<HTMLMSegmentControlItemElement>;
            "m-select": LocalJSX.MSelect & JSXBase.HTMLAttributes<HTMLMSelectElement>;
            "m-shortcut-toggle": LocalJSX.MShortcutToggle & JSXBase.HTMLAttributes<HTMLMShortcutToggleElement>;
        }
    }
}
