/**
 * generate-hooks.mjs
 *
 * Generates docs/api.json — a unified public API descriptor for Dynamic UI.
 * Merges:
 *   - component props from docs/props.json (generated by generate-props.mjs)
 *   - hook signatures extracted via TypeScript Compiler API
 *
 * Hook extraction covers exported types, JSDoc (description, @requires, @param),
 * and call signatures — information that react-docgen-typescript cannot provide
 * because it only processes React components, not plain functions.
 *
 * Prerequisite: docs/ directory must exist (run `npm run build:storybook` first).
 * Usage: node scripts/generate-hooks.mjs
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
const ts = require('typescript');

const dirPath = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(dirPath, '..');

// --- Validation ---
const OUTPUT_DIR = resolve(ROOT, 'docs');
if (!existsSync(OUTPUT_DIR)) {
  process.stderr.write('docs/ not found. Run `npm run build:storybook` first.\n');
  process.exit(1);
}

const TSCONFIG_PATH = resolve(ROOT, 'tsconfig.json');
if (!existsSync(TSCONFIG_PATH)) {
  process.stderr.write('tsconfig.json not found at project root.\n');
  process.exit(1);
}

// --- Public hook files to document (relative to project root) ---
const HOOK_FILES = [
  'src/components/DToastContainer/useDToast.tsx',
];

// --- Load tsconfig ---
const tsConfigFile = ts.readConfigFile(TSCONFIG_PATH, ts.sys.readFile);
const { options: compilerOptions } = ts.parseJsonConfigFileContent(
  tsConfigFile.config,
  ts.sys,
  dirname(TSCONFIG_PATH),
);

// --- Helpers ---

/** Extracts plain text from a JSDoc comment (string or NodeArray). */
function jsDocCommentToString(comment) {
  if (!comment) return '';
  if (typeof comment === 'string') return comment.trim();
  return ts.displayPartsToString(comment).trim();
}

/** Reads the JSDoc text attached directly to a node via ts.getJSDocCommentsAndTags. */
function getNodeJsDoc(node) {
  return ts.getJSDocCommentsAndTags(node)
    .map((d) => jsDocCommentToString(d.comment))
    .filter(Boolean)
    .join('\n')
    .trim();
}

/** Returns the raw source text of a TypeNode (best-effort inline type display). */
function typeNodeText(typeNode, sourceFile) {
  if (!typeNode) return 'unknown';
  return typeNode.getText(sourceFile).replace(/\s+/g, ' ').trim();
}

/**
 * Resolves a TypeScript Type to a self-contained serializable descriptor.
 *
 * - String-literal union  → { type: 'string', values: ['a', 'b', ...] }
 * - Object / mapped type  → { type: 'object', fields: { prop: { type, required, description } } }
 * - Scalar / other        → { type: '<checker string>' }
 *
 * Union members that are `undefined` are stripped so optional properties stay clean
 * (the `required` flag on the parent field already captures optionality).
 * Recursion is capped at depth 3 to avoid expanding deep library internals.
 */
function resolveTypeInfo(type, checker, locationNode, depth = 0) {
  if (depth > 3) return { type: checker.typeToString(type) };

  // Guard primitive types before getPropertiesOfType, which would otherwise
  // return String/Number interface methods for primitive string/number.
  // eslint-disable-next-line no-bitwise
  if (type.flags & ts.TypeFlags.String) return { type: 'string' };
  // eslint-disable-next-line no-bitwise
  if (type.flags & ts.TypeFlags.Number) return { type: 'number' };
  // eslint-disable-next-line no-bitwise
  if (type.flags & ts.TypeFlags.Boolean) return { type: 'boolean' };

  if (type.isUnion()) {
    // eslint-disable-next-line no-bitwise
    const nonUndefined = type.types.filter((t) => !(t.flags & ts.TypeFlags.Undefined));

    if (nonUndefined.length > 0 && nonUndefined.every((t) => t.isStringLiteral())) {
      return { type: 'string', values: nonUndefined.map((t) => t.value) };
    }
    if (nonUndefined.length === 1) {
      return resolveTypeInfo(nonUndefined[0], checker, locationNode, depth);
    }
    return { type: checker.typeToString(type) };
  }

  // Object / mapped type (TypeLiteral, interface, Partial<Pick<...>>, etc.)
  const props = checker.getPropertiesOfType(type);
  if (props.length > 0) {
    const fields = {};
    props.forEach((prop) => {
      const propType = checker.getTypeOfSymbolAtLocation(prop, locationNode);
      // eslint-disable-next-line no-bitwise
      const isOptional = !!(Number(prop.flags) & Number(ts.SymbolFlags.Optional));
      const desc = ts.displayPartsToString(prop.getDocumentationComment(checker)).trim();
      fields[prop.name] = {
        ...resolveTypeInfo(propType, checker, locationNode, depth + 1),
        required: !isOptional,
        ...(desc ? { description: desc } : {}),
      };
    });
    return { type: 'object', fields };
  }

  return { type: checker.typeToString(type) };
}

/**
 * Reads `@param` JSDoc tags from a node and returns name → description map.
 * This handles inline-documented parameters (e.g. on `useCallback` wrappers)
 * that are not accessible via the type checker's documentation comments.
 */
function getJsDocParamDescriptions(node) {
  return ts.getJSDocTags(node).reduce((result, tag) => {
    if (!ts.isJSDocParameterTag(tag) || !tag.name) return result;
    const raw = tag.name.getText ? tag.name.getText() : String(tag.name);
    const name = raw.replace(/^-?\s*/, '').trim();
    return {
      ...result,
      [name]: jsDocCommentToString(tag.comment).replace(/^-\s*/, '').trim(),
    };
  }, {});
}

/**
 * Reads `@requires` JSDoc tags from a node and returns an ordered string array.
 * Used to document prerequisites (context providers, companion components) for a hook.
 */
function getJsDocRequires(node) {
  return ts.getJSDocTags(node)
    .filter((tag) => tag.tagName && tag.tagName.text === 'requires')
    .map((tag) => jsDocCommentToString(tag.comment))
    .filter(Boolean);
}

/**
 * Extracts the call parameters of a function-typed symbol using the type checker.
 * Returns [{ name, type, required, description }].
 */
function extractCallParams(symbol, checker, locationNode) {
  const type = checker.getTypeOfSymbolAtLocation(symbol, locationNode);
  const sigs = checker.getSignaturesOfType(type, ts.SignatureKind.Call);
  if (!sigs.length) return [];
  return sigs[0].parameters.map((param) => ({
    name: param.name,
    type: checker.typeToString(
      checker.getTypeOfSymbolAtLocation(param, locationNode),
    ),
    required: /* eslint-disable-next-line no-bitwise */
      !(Number(param.flags) & Number(ts.SymbolFlags.Optional)),
    description: ts.displayPartsToString(
      param.getDocumentationComment(checker),
    ).trim(),
  }));
}

/**
 * Returns the string representation of the return type of a function-typed symbol.
 */
function extractReturnTypeString(symbol, checker, locationNode) {
  const type = checker.getTypeOfSymbolAtLocation(symbol, locationNode);
  const sigs = checker.getSignaturesOfType(type, ts.SignatureKind.Call);
  if (!sigs.length) return 'void';
  return checker.typeToString(checker.getReturnTypeOfSignature(sigs[0]));
}

/**
 * Builds a TypeScript-style signature string for a hook.
 * Example: `useDToast() => { toast }`
 */
function buildSignature(hookName, parameters, returnKeys) {
  const params = parameters
    .map((p) => `${p.name}${p.required ? '' : '?'}: ${p.type}`)
    .join(', ');
  const ret = returnKeys.length ? `{ ${returnKeys.join(', ')} }` : 'void';
  return `${hookName}(${params}) => ${ret}`;
}

// --- Core extraction ---

/**
 * Parses a hook source file and returns a structured API descriptor:
 * {
 *   source,        // relative file path
 *   description,   // hook JSDoc
 *   requires,      // prerequisite components/providers (@requires tags)
 *   signature,     // TypeScript-style function signature
 *   parameters,    // hook function parameters (usually empty for React hooks)
 *   returns,       // map of returned properties → their call signature
 *   types,         // exported type aliases with field descriptions
 * }
 */
function extractHookDoc(relPath) {
  const filePath = resolve(ROOT, relPath);
  if (!existsSync(filePath)) throw new Error(`File not found: ${filePath}`);

  const program = ts.createProgram([filePath], { ...compilerOptions, noEmit: true });
  const checker = program.getTypeChecker();
  const sourceFile = program.getSourceFile(filePath);
  if (!sourceFile) throw new Error(`Could not load source file: ${filePath}`);

  const hookName = relPath.split('/').pop().replace(/\.(tsx?|jsx?)$/, '');
  const doc = {
    source: relPath,
    description: '',
    requires: [],
    signature: '',
    parameters: [],
    returns: {},
    types: {},
  };

  ts.forEachChild(sourceFile, (node) => {
    // eslint-disable-next-line no-bitwise
    const flags = ts.getCombinedModifierFlags(node);
    // eslint-disable-next-line no-bitwise
    const isExported = (flags & ts.ModifierFlags.Export) !== 0;
    // eslint-disable-next-line no-bitwise
    const isDefault = (flags & ts.ModifierFlags.Default) !== 0;

    // Collect exported type aliases and interfaces — fully resolved via the type checker
    // so referenced types (e.g. ComponentStateColor) are expanded inline.
    const isExportedTypeOrInterface = isExported
      && (ts.isTypeAliasDeclaration(node) || ts.isInterfaceDeclaration(node));
    if (isExportedTypeOrInterface) {
      const declType = checker.getTypeAtLocation(node.name);
      doc.types[node.name.text] = {
        description: getNodeJsDoc(node),
        ...resolveTypeInfo(declType, checker, node),
      };
    }

    // Process the default-exported hook function
    if (ts.isFunctionDeclaration(node) && isExported && isDefault) {
      doc.description = getNodeJsDoc(node);
      doc.requires = getJsDocRequires(node);

      // Hook-level parameters (typically none for React hooks)
      doc.parameters = (node.parameters ?? []).map((param) => ({
        name: param.name.getText(sourceFile),
        type: typeNodeText(param.type, sourceFile),
        required: !param.questionToken && !param.initializer,
        description: getNodeJsDoc(param),
      }));

      // Collect JSDoc from `const x = useCallback(...)` declarations inside the body.
      // TypeScript attaches doc comments to variable declarations, not return symbols,
      // so we pre-build maps of variable name → { description, paramDescriptions }
      // for the return enrichment step.
      const innerJsDoc = {};
      const innerParamDescriptions = {};
      if (node.body) {
        ts.forEachChild(node.body, (stmt) => {
          if (
            ts.isVariableStatement(stmt)
            && stmt.declarationList
            && stmt.declarationList.declarations.length
          ) {
            const decl = stmt.declarationList.declarations[0];
            if (decl.name && ts.isIdentifier(decl.name)) {
              const jsDoc = getNodeJsDoc(stmt);
              if (jsDoc) innerJsDoc[decl.name.text] = jsDoc;
              const paramMap = getJsDocParamDescriptions(stmt);
              if (Object.keys(paramMap).length) {
                innerParamDescriptions[decl.name.text] = paramMap;
              }
            }
          }
        });
      }

      // Use the type checker to inspect the hook's return type
      if (node.name) {
        const hookSymbol = checker.getSymbolAtLocation(node.name);
        if (hookSymbol) {
          const hookType = checker.getTypeOfSymbolAtLocation(hookSymbol, node);
          const sigs = checker.getSignaturesOfType(hookType, ts.SignatureKind.Call);
          if (sigs.length) {
            const returnType = checker.getReturnTypeOfSignature(sigs[0]);
            checker.getPropertiesOfType(returnType).forEach((prop) => {
              const symbolDoc = ts.displayPartsToString(
                prop.getDocumentationComment(checker),
              ).trim();
              doc.returns[prop.name] = {
                description: symbolDoc || innerJsDoc[prop.name] || '',
                parameters: extractCallParams(prop, checker, node).map((p) => ({
                  ...p,
                  description:
                    p.description
                    || (innerParamDescriptions[prop.name] ?? {})[p.name]
                    || '',
                })),
                returns: {
                  type: extractReturnTypeString(prop, checker, node),
                },
              };
            });
          }
        }
      }

      doc.signature = buildSignature(hookName, doc.parameters, Object.keys(doc.returns));
    }
  });

  return doc;
}

// --- Run ---
process.stdout.write('Generating docs/api.json...\n');
const hooksSection = {};
let failed = 0;

HOOK_FILES.forEach((relPath) => {
  const hookName = relPath.split('/').pop().replace(/\.(tsx?|jsx?)$/, '');
  try {
    hooksSection[hookName] = extractHookDoc(relPath);
    process.stdout.write(`  ok ${hookName}\n`);
  } catch (err) {
    process.stderr.write(`  FAIL ${hookName}: ${err.message}\n`);
    failed += 1;
  }
});

// Merge component props from docs/props.json into the unified output
const PROPS_PATH = resolve(OUTPUT_DIR, 'props.json');
const componentsSection = {};
if (existsSync(PROPS_PATH)) {
  const propsRaw = readFileSync(PROPS_PATH, 'utf8');
  const propsData = JSON.parse(propsRaw);
  Object.entries(propsData).forEach(([name, data]) => {
    componentsSection[name] = { props: data.props ?? {} };
  });
  process.stdout.write(`  merged ${Object.keys(componentsSection).length} components from props.json\n`);
}

const { version } = JSON.parse(readFileSync(resolve(ROOT, 'package.json'), 'utf8'));

const apiOutput = {
  $schema: 'https://raw.githubusercontent.com/dynamic-framework/dynamic-ui/refs/heads/main/docs/api.schema.json',
  version,
  components: componentsSection,
  hooks: hooksSection,
};

const OUTPUT_PATH = resolve(OUTPUT_DIR, 'api.json');
const output = JSON.stringify(apiOutput, null, 2);
writeFileSync(OUTPUT_PATH, output);

const sizeKB = (Buffer.byteLength(output) / 1024).toFixed(1);
process.stdout.write('\nGenerated docs/api.json\n');
process.stdout.write(`  Hooks: ${Object.keys(hooksSection).length} documented, ${failed} failed\n`);
process.stdout.write(`  Components: ${Object.keys(componentsSection).length} included\n`);
process.stdout.write(`  Size: ${sizeKB} KB\n`);

if (failed > 0) {
  process.stderr.write(`\n${failed} hooks failed\n`);
  process.exit(1);
}
