/**
 * generate-schema.mjs
 *
 * Generates registry/schema/v1.json — the JSON Schema for registry/api.json.
 * This schema is referenced by the $schema field in api.json and allows
 * consumers and tools to validate the contract structure.
 *
 * Usage: node scripts/generate-schema.mjs
 */

import { mkdirSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const dirPath = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(dirPath, '..');
const OUTPUT_DIR = resolve(ROOT, 'registry');

if (!existsSync(OUTPUT_DIR)) {
  mkdirSync(OUTPUT_DIR, { recursive: true });
}

const propSchema = {
  type: 'object',
  additionalProperties: false,
  required: ['type'],
  properties: {
    type: { type: 'string', description: 'TypeScript type as a string.' },
    required: { type: 'boolean' },
    defaultValue: { type: ['string', 'number', 'boolean', 'null'] },
    description: { type: 'string' },
  },
};

const schema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://cdn.dynamicframework.dev/assets/schema/v1.json',
  title: 'Dynamic UI — api.json contract v1',
  description:
    'Describes the structure of registry/api.json generated by the Dynamic UI build pipeline.',
  type: 'object',
  required: ['$schema', 'schemaVersion', 'packageVersion', 'generatedAt', 'components', 'hooks', 'contexts'],
  additionalProperties: false,
  properties: {
    $schema: {
      type: 'string',
      format: 'uri',
      description: 'URI of this JSON Schema.',
    },
    schemaVersion: {
      type: 'string',
      pattern: '^\\d+\\.\\d+\\.\\d+$',
      description: 'Version of this schema structure (independent of the package version).',
    },
    packageVersion: {
      type: 'string',
      pattern: '^\\d+\\.\\d+\\.\\d+.*$',
      description: 'npm package version of @dynamic-framework/ui-react that produced this file.',
    },
    generatedAt: {
      type: 'string',
      format: 'date-time',
      description: 'ISO-8601 timestamp of when api.json was generated.',
    },
    components: {
      type: 'object',
      description: 'React component prop tables, keyed by component name.',
      additionalProperties: {
        type: 'object',
        required: ['description', 'props'],
        additionalProperties: false,
        properties: {
          description: { type: 'string' },
          sourcePath: {
            type: 'string',
            description: 'Relative path from the repo root to the source file.',
          },
          props: {
            type: 'object',
            additionalProperties: propSchema,
          },
        },
      },
    },
    hooks: {
      type: 'object',
      description: 'Custom React hook signatures, keyed by hook name.',
      additionalProperties: {
        type: 'object',
        required: ['description'],
        properties: {
          description: { type: 'string' },
          requires: {
            type: 'array',
            items: { type: 'string' },
          },
          params: {
            type: 'array',
            items: {
              type: 'object',
              required: ['name', 'type'],
              properties: {
                name: { type: 'string' },
                type: { type: 'string' },
                required: { type: 'boolean' },
                description: { type: 'string' },
              },
            },
          },
          returns: {
            type: 'object',
            additionalProperties: {
              type: 'object',
              required: ['type'],
              properties: {
                type: {
                  type: 'string',
                  description: 'TypeScript type string, or "function" for callable values.',
                },
                description: { type: 'string' },
                parameters: {
                  type: 'array',
                  description: 'Present when type is "function".',
                  items: {
                    type: 'object',
                    required: ['name', 'type'],
                    properties: {
                      name: { type: 'string' },
                      type: { type: 'string' },
                      required: { type: 'boolean' },
                      description: { type: 'string' },
                    },
                  },
                },
                returns: {
                  type: 'object',
                  description: 'Return type of the function. Present when type is "function".',
                  properties: {
                    type: { type: 'string' },
                  },
                },
              },
            },
          },
        },
      },
    },
    contexts: {
      type: 'object',
      description: 'React context values, keyed by context/hook name.',
      additionalProperties: {
        type: 'object',
        required: ['description'],
        properties: {
          description: { type: 'string' },
          requires: {
            type: 'array',
            items: { type: 'string' },
          },
          returns: {
            type: 'object',
            additionalProperties: {
              type: 'object',
              required: ['type'],
              properties: {
                type: {
                  type: 'string',
                  description: 'TypeScript type string, or "function" for callable values.',
                },
                description: { type: 'string' },
                parameters: {
                  type: 'array',
                  description: 'Present when type is "function".',
                  items: {
                    type: 'object',
                    required: ['name', 'type'],
                    properties: {
                      name: { type: 'string' },
                      type: { type: 'string' },
                      required: { type: 'boolean' },
                      description: { type: 'string' },
                    },
                  },
                },
                returns: {
                  type: 'object',
                  description: 'Return type of the function. Present when type is "function".',
                  properties: {
                    type: { type: 'string' },
                  },
                },
              },
            },
          },
        },
      },
    },
  },
};

const SCHEMA_DIR = resolve(OUTPUT_DIR, 'schema');
mkdirSync(SCHEMA_DIR, { recursive: true });

const SCHEMA_PATH = resolve(SCHEMA_DIR, 'v1.json');
writeFileSync(SCHEMA_PATH, JSON.stringify(schema, null, 2));
process.stdout.write('Generated registry/schema/v1.json\n');
