/**
 * generate-a11y-browser-warnings.ts
 *
 * Runs the axe-core rules that CANNOT be reliably validated in jsdom
 * (color-contrast, link-in-text-block — see tests/a11y/axeHelper.ts)
 * against a real, headless browser using Playwright, targeting every
 * Storybook story.
 *
 * This is intentionally scoped and separate from `generate-a11y-report.ts`
 * (which runs the full wcag2a/wcag2aa rule set on demand/locally):
 *   - Only the rules that need real rendering/paint are checked here, to
 *     avoid re-checking what jest-axe already covers per component and to
 *     keep each page scan fast. (color-contrast-enhanced / AAA is
 *     intentionally excluded too — see README note near BROWSER_ONLY_RULES.)
 *   - Every violation is classified as "own" (design system markup) or
 *     "third-party" (generated by a vendor dependency we don't control),
 *     using scripts/a11y-third-party-patterns.ts.
 *   - For now this NEVER fails the build: violations are printed as
 *     GitHub Actions `::warning::` annotations to the console, as soon as
 *     each story is analyzed. Only genuine tooling failures (Storybook
 *     not built, browser crash, etc.) exit non-zero.
 *
 * Usage:
 *   npm run build
 *   npm run build:storybook
 *   npx tsx scripts/generate-a11y-browser-warnings.ts
 */

import { chromium, Browser, Page } from 'playwright';
import type { AxeResults, Result, NodeResult } from 'axe-core';
import * as fs from 'fs';
import * as path from 'path';
import * as http from 'http';
import { matchThirdPartyPattern } from './a11y-third-party-patterns';

// ─── Config ─────────────────────────────────────────────────────────────────

// npm run build:storybook always outputs here (see package.json).
const STORYBOOK_DIR = path.resolve('./docs');
const PORT = Number(process.env.PORT) || 4174;
const STORYBOOK_URL = `http://127.0.0.1:${PORT}`;
const TIMEOUT_MS = 15000;
const BASE_INCLUDE = 'Design System/Components';

// Only the rules jest-axe disables by default because jsdom cannot
// paint/layout content (see tests/a11y/axeHelper.ts). Note:
// color-contrast-enhanced (WCAG AAA) is intentionally excluded — it's an
// optional, stricter-than-usual threshold disabled by default in
// axe-core itself, and checking it against this design system's current
// palette produces mostly noise (~40x more hits than the actual AA
// baseline) rather than actionable findings.
const BROWSER_ONLY_RULES = ['color-contrast', 'link-in-text-block'];

const AXE_SOURCE = fs.readFileSync(
  path.resolve('./node_modules/axe-core/axe.min.js'),
  'utf-8',
);

// ─── Types ──────────────────────────────────────────────────────────────────

interface Story {
  id: string;
  title: string;
  name: string;
  type: string;
}

type Origin = 'own' | 'third-party';

interface ClassifiedNode {
  html: string;
  target: string[];
  origin: Origin;
  library?: string;
}

interface ClassifiedViolation {
  ruleId: string;
  impact: string | null | undefined;
  help: string;
  nodes: ClassifiedNode[];
  origins: Origin[];
}

// ─── Minimal static file server (no extra dependency) ──────────────────────

const MIME_TYPES: Record<string, string> = {
  '.html': 'text/html',
  '.js': 'text/javascript',
  '.mjs': 'text/javascript',
  '.css': 'text/css',
  '.json': 'application/json',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
};

function startStaticServer(rootDir: string, port: number): Promise<http.Server> {
  const server = http.createServer((req, res) => {
    const requestPath = decodeURIComponent((req.url || '/').split('?')[0]);
    const safePath = path.normalize(requestPath).replace(/^(\.\.[/\\])+/, '');
    let filePath = path.join(rootDir, safePath);

    if (!fs.existsSync(filePath) || fs.statSync(filePath).isDirectory()) {
      filePath = path.join(rootDir, 'index.html');
    }

    fs.readFile(filePath, (err, content) => {
      if (err) {
        res.writeHead(404);
        res.end('Not found');
        return;
      }
      const ext = path.extname(filePath);
      res.writeHead(200, { 'Content-Type': MIME_TYPES[ext] || 'application/octet-stream' });
      res.end(content);
    });
  });

  return new Promise((resolve, reject) => {
    server.on('error', reject);
    server.listen(port, () => resolve(server));
  });
}

// ─── Story discovery ────────────────────────────────────────────────────────

async function fetchStories(page: Page): Promise<Story[]> {
  await page.goto(`${STORYBOOK_URL}/index.json`, { timeout: TIMEOUT_MS });
  const raw = await page.evaluate(() => document.body.innerText);
  const index = JSON.parse(raw) as { entries: Record<string, Story> };
  return Object.values(index.entries).filter(
    (entry) => entry.type === 'story' && entry.title.startsWith(BASE_INCLUDE),
  );
}

// ─── Violation classification ──────────────────────────────────────────────

function classifyViolation(violation: Result, storyTitle: string): ClassifiedViolation {
  const nodes: ClassifiedNode[] = violation.nodes.map((node: NodeResult) => {
    const match = matchThirdPartyPattern(node.html, violation.id, storyTitle);
    return {
      html: node.html,
      target: node.target as string[],
      origin: match ? 'third-party' : 'own',
      library: match?.library,
    };
  });

  return {
    ruleId: violation.id,
    impact: violation.impact,
    help: violation.help,
    nodes,
    origins: Array.from(new Set(nodes.map((n) => n.origin))),
  };
}

async function analyzeStory(
  page: Page,
  story: Story,
): Promise<{ violations: ClassifiedViolation[]; error?: string }> {
  const url = `${STORYBOOK_URL}/iframe.html?id=${story.id}&viewMode=story`;

  try {
    await page.goto(url, { waitUntil: 'networkidle', timeout: TIMEOUT_MS });
    await page.waitForSelector('#storybook-root, #root', { timeout: TIMEOUT_MS });
    await page.addScriptTag({ content: AXE_SOURCE });

    const results: AxeResults = await page.evaluate(
      (rules) => (window as any).axe.run('#storybook-root, #root', {
        runOnly: { type: 'rule', values: rules },
      }),
      BROWSER_ONLY_RULES,
    );

    return { violations: results.violations.map((v) => classifyViolation(v, story.title)) };
  } catch (err: any) {
    return { violations: [], error: err?.message ?? String(err) };
  }
}

// ─── Reporting (console + GitHub Actions annotations only) ────────────────

function printWarningAnnotation(story: Story, url: string, violation: ClassifiedViolation): void {
  const originLabel = violation.origins.includes('own') ? 'own' : 'third-party';
  const libraries = Array.from(
    new Set(violation.nodes.map((n) => n.library).filter(Boolean)),
  ).join(', ');
  const suffix = libraries ? ` via ${libraries}` : '';

  // GitHub Actions parses "::warning::" lines from stdout and surfaces
  // them in the run's "Annotations" section, regardless of when during
  // the job they're printed.
  console.log(
    `::warning title=a11y (${originLabel}${suffix})::[${story.title} / ${story.name}] `
      + `${violation.ruleId}: ${violation.help} — ${violation.nodes.length} node(s). ${url}`,
  );
}

// ─── Main ───────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  console.log('🔍  Starting browser-only accessibility audit…');
  console.log(`   Storybook dir : ${STORYBOOK_DIR}`);
  console.log(`   Rules checked : ${BROWSER_ONLY_RULES.join(', ')}`);

  if (!fs.existsSync(path.join(STORYBOOK_DIR, 'index.html'))) {
    console.error(`::error::Storybook build not found at "${STORYBOOK_DIR}". Run "npm run build" and "npm run build:storybook" first.`);
    process.exit(1);
  }

  let server: http.Server;
  let browser: Browser;

  try {
    server = await startStaticServer(STORYBOOK_DIR, PORT);
  } catch (err) {
    console.error('::error::Could not start the local Storybook static server.', err);
    process.exit(1);
    return;
  }

  try {
    browser = await chromium.launch();
  } catch (err) {
    console.error('::error::Could not launch the Playwright browser.', err);
    server.close();
    process.exit(1);
    return;
  }

  const page = await browser.newPage();
  let stories: Story[] = [];

  try {
    stories = await fetchStories(page);
    console.log(`   Found ${stories.length} stories under "${BASE_INCLUDE}"\n`);
  } catch (err) {
    console.error('::error::Could not fetch the Storybook story index.', err);
    await browser.close();
    server.close();
    process.exit(1);
    return;
  }

  let ownCount = 0;
  let thirdPartyCount = 0;
  let storiesWithViolations = 0;
  let erroredCount = 0;

  for (const story of stories) {
    // eslint-disable-next-line no-await-in-loop
    const { violations, error } = await analyzeStory(page, story);
    const url = `${STORYBOOK_URL}/iframe.html?id=${story.id}&viewMode=story`;

    if (error) {
      erroredCount += 1;
      console.log(`::warning title=a11y (scan error)::[${story.title} / ${story.name}] Could not be analyzed: ${error}`);
    } else if (violations.length > 0) {
      storiesWithViolations += 1;
      violations.forEach((violation) => {
        if (violation.origins.includes('own')) ownCount += 1;
        else thirdPartyCount += 1;
        printWarningAnnotation(story, url, violation);
      });
    }
  }

  await browser.close();
  server.close();

  console.log('\n── Summary ─────────────────────────────');
  console.log(`   Stories analyzed          : ${stories.length}`);
  console.log(`   Stories with violations   : ${storiesWithViolations}`);
  console.log(`   Own component violations : ${ownCount}`);
  console.log(`   Third-party violations    : ${thirdPartyCount}`);
  if (erroredCount > 0) console.log(`   Stories that errored      : ${erroredCount}`);
  console.log('────────────────────────────────────────\n');
  console.log('⚠️  These checks are non-blocking (warnings only) for now.');

  // Intentionally always exits 0: violations are surfaced as warnings only
  // while the own-vs-third-party classification is validated in practice.
  process.exit(0);
}

main().catch((err) => {
  console.error('::error::Unexpected failure running the browser accessibility audit.', err);
  process.exit(1);
});
