/**
 * generate-tokens.mjs
 *
 * Generates registry/tokens.json — a DTCG (2025.10) color contract for
 * Dynamic UI, phase 1: the full color subtree (10 chromatic families + gray)
 * with literal values in `$value` plus the tint relationship per family in
 * `$extensions` ("2a + tint relation via extensions").
 *
 * SOURCE OF TRUTH (SPEC R1): values are read from the SCSS source by compiling
 * a dedicated, throwaway harness (scripts/tokens/_export-harness.scss) with the
 * project's dart-sass (SPEC R2) — NOT by parsing the 1.27 MB compiled CSS
 * (which carries the dead `--bs---bs-ref-spacer-4` token and loses the
 * literal-vs-derived intent).
 *
 * The 11 ramp weights are KNOWN CONSTANTS documented in
 * src/style/abstracts/variables/_colors.scss (tint-color/shade-color calls).
 * They are carried here with their provenance; they are NOT inferred from the
 * harness output. The harness output only supplies the resolved hex values.
 *
 * Usage: node scripts/generate-tokens.mjs
 */

import { execFileSync } from 'node:child_process';
import {
  mkdirSync, writeFileSync, mkdtempSync, rmSync, readFileSync,
} from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(SCRIPT_DIR, '..');
const SASS_BIN = resolve(ROOT, 'node_modules/.bin/sass'); // R2: never the PATH `sass`
const HARNESS = resolve(SCRIPT_DIR, 'tokens/_export-harness.scss');
const OUTPUT_DIR = resolve(ROOT, 'registry');
const OUTPUT_PATH = resolve(OUTPUT_DIR, 'tokens.json');

const SCHEMA_VERSION = '1.0.0';
const CDN_BASE = 'https://cdn.dynamicframework.dev/assets';

// The 11-step tint curve, verbatim from _colors.scss. `op` uses lighten/darken
// (Tokens Studio `modify` convention) instead of signed weights, per SPEC §5.2:
//   lighten w  ==  tint-color(base, w*100%)  ==  mix(white, base, w*100%)
//   darken  w  ==  shade-color(base, w*100%) ==  mix(black, base, w*100%)
// All mixing is sRGB (Bootstrap's mix()).
const RAMP = [
  { step: '25', op: 'lighten', weight: 0.95 },
  { step: '50', op: 'lighten', weight: 0.90 },
  { step: '100', op: 'lighten', weight: 0.80 },
  { step: '200', op: 'lighten', weight: 0.60 },
  { step: '300', op: 'lighten', weight: 0.40 },
  { step: '400', op: 'lighten', weight: 0.20 },
  { step: '500', op: 'base' },
  { step: '600', op: 'darken', weight: 0.20 },
  { step: '700', op: 'darken', weight: 0.40 },
  { step: '800', op: 'darken', weight: 0.60 },
  { step: '900', op: 'darken', weight: 0.80 },
];

// Families generated by tint-color/shade-color in _colors.scss → exact bootstrap-mix.
const CHROMATIC = ['blue', 'indigo', 'purple', 'pink', 'red', 'orange', 'yellow', 'green', 'teal', 'cyan'];
// Gray is a hand-authored neutral scale (NOT mix-generated): see §audit below.
const GRAY = 'gray';
const ALL_FAMILIES = [...CHROMATIC, GRAY];

/**
 * Role consistency audit (SPEC §5.4, R4: report, do NOT fix the source).
 * Derived from read-only inspection of _colors.scss and _root.scss; documented
 * here because the contract does not re-emit the role ramps that expose the bug.
 */
const ROLE_AUDIT = {
  secondary: {
    consistent: false,
    issue:
      'The role maps to gray-800, but the runtime ramp step --bs-secondary-500 '
      + 'inherits that value via the -500 special case in _root.scss, breaking '
      + 'monotonicity: --bs-secondary-400 = gray-400 (138,138,155), '
      + '--bs-secondary-500 = gray-800 (43,43,52), --bs-secondary-600 = gray-600 (87,87,104).',
    scssDivergence: '$secondary (gray-400) != runtime --bs-secondary (gray-800)',
  },
  warning: {
    consistent: false,
    issue:
      'The warning role is manually special-cased in _root.scss (btn-soft-warning '
      + 'forces -800 text) and $warning-text-emphasis uses -800 while every other '
      + 'role uses -600. These deviations are in the semantic/button layer (out of '
      + 'phase-1 scope); the warning COLOR ramp itself follows yellow and is consistent.',
    colorRampConsistent: true,
  },
};

function compileHarness() {
  const tmp = mkdtempSync(join(tmpdir(), 'dtcg-harness-'));
  const out = join(tmp, 'harness.css');
  try {
    execFileSync(
      SASS_BIN,
      ['--no-source-map', '--load-path=src/style', '--load-path=./', HARNESS, out],
      { cwd: ROOT, stdio: ['ignore', 'ignore', 'inherit'] },
    );
    return { css: readFileSync(out, 'utf8'), tmp };
  } catch (err) {
    rmSync(tmp, { recursive: true, force: true });
    throw err;
  }
}

/** Parse `--ramp-<fam>-<step>`, `--base-<fam>`, `--map-<role>` from the harness CSS. */
function parseHarness(css) {
  const ramps = {}; // fam -> { step -> hex }
  const bases = {}; // fam -> hex
  const mapping = {}; // role -> target string

  const declRe = /--(ramp|base|map)-([a-z0-9-]+):\s*([^;]+);/g;
  let m;
  while ((m = declRe.exec(css)) !== null) {
    const [, kind, key, rawValue] = m;
    const value = rawValue.trim();
    if (kind === 'base') {
      bases[key] = value.toLowerCase();
    } else if (kind === 'map') {
      mapping[key] = value.replace(/^"|"$/g, ''); // strip quotes
    } else { // ramp: key is "<fam>-<step>"
      const idx = key.lastIndexOf('-');
      const fam = key.slice(0, idx);
      const step = key.slice(idx + 1);
      (ramps[fam] ||= {})[step] = value.toLowerCase();
    }
  }
  return { ramps, bases, mapping };
}

/** Build the DTCG node for one family (leaf base value + nested ramp + tint ext). */
function buildFamily(fam, ramp, base, isMix) {
  const node = {
    $type: 'color',
    // The family name with no step IS the base/-500 (source: $colors.<fam> == <fam>-500),
    // emitted as a leaf so `{color.<fam>}` resolves as the base alias (SPEC §5.2 note).
    $value: base,
  };

  for (const { step } of RAMP) {
    node[step] = step === '500'
      ? { $value: `{color.${fam}}` } // -500 is an alias to the base (SPEC §5.2)
      : { $value: ramp[step] };
  }

  const steps = {};
  for (const { step, op, weight } of RAMP) {
    steps[step] = op === 'base' ? { op } : { op, weight };
  }

  node.$extensions = {
    'dev.dynamicframework.tint': {
      base: `{color.${fam}}`,
      space: 'srgb',
      // Honesty (R5/§7): only the chromatic families are actually generated by
      // mix(); gray is a hand-tuned neutral scale that only approximates it.
      method: isMix ? 'bootstrap-mix' : 'hand-authored',
      ...(isMix ? {} : {
        fidelity: 'approximate',
        note:
          'Gray is authored as literal values in _colors.scss, not generated by '
          + 'tint-color/shade-color. The weights below describe the nominal intent; '
          + 'several steps deviate from exact bootstrap-mix by ~1 per channel.',
      }),
      steps,
    },
  };
  return node;
}

/** Resolve a $theme-colors-mapping target to a DTCG alias (family OR step). */
function targetToAlias(target) {
  // Step form "<fam>-<step>" (e.g. gray-800) -> {color.fam.step}; else family -> {color.fam}.
  const stepMatch = /^([a-z]+)-(\d{2,3})$/.exec(target);
  if (stepMatch && ALL_FAMILIES.includes(stepMatch[1])) {
    return `{color.${stepMatch[1]}.${stepMatch[2]}}`;
  }
  if (ALL_FAMILIES.includes(target)) {
    return `{color.${target}}`;
  }
  throw new Error(`Unresolvable role target: "${target}"`);
}

function buildRole(role, target) {
  const node = { $type: 'color', $value: targetToAlias(target) };
  const audit = ROLE_AUDIT[role];
  if (audit) {
    node.$extensions = { 'dev.dynamicframework.audit': audit };
  }
  return node;
}

function main() {
  const { version } = JSON.parse(readFileSync(resolve(ROOT, 'package.json'), 'utf8'));

  process.stdout.write('Compiling export harness with dart-sass...\n');
  const { css, tmp } = compileHarness();
  let parsed;
  try {
    parsed = parseHarness(css);
  } finally {
    rmSync(tmp, { recursive: true, force: true }); // no temp artifacts (SPEC §3)
  }
  const { ramps, bases, mapping } = parsed;

  // Sanity: every family must have a base and a full 11-step ramp.
  for (const fam of ALL_FAMILIES) {
    if (!bases[fam]) throw new Error(`Missing base for family "${fam}"`);
    for (const { step } of RAMP) {
      if (!ramps[fam]?.[step]) throw new Error(`Missing ${fam}-${step} in harness output`);
    }
  }

  const color = {};
  for (const fam of ALL_FAMILIES) {
    color[fam] = buildFamily(fam, ramps[fam], bases[fam], CHROMATIC.includes(fam));
  }
  for (const [role, target] of Object.entries(mapping)) {
    color[role] = buildRole(role, target);
  }

  const tokens = {
    $schema: `${CDN_BASE}/${version}/tokens/schema/tokens.v1.json`,
    $extensions: {
      'dev.dynamicframework.contract': {
        schemaVersion: SCHEMA_VERSION,
        dynamicUi: version,
        generatedFrom: 'scss-source',
      },
    },
    color,
  };

  mkdirSync(OUTPUT_DIR, { recursive: true });
  writeFileSync(OUTPUT_PATH, `${JSON.stringify(tokens, null, 2)}\n`, 'utf8');
  process.stdout.write(`Generated ${OUTPUT_PATH}\n`);
  process.stdout.write(
    `  ${ALL_FAMILIES.length} families, ${Object.keys(mapping).length} roles, `
    + `dynamicUi ${version}\n`,
  );
}

main();
