/*
 * GENERATED by scripts/storybook/build-manager-theme.mjs. Do not edit.
 *
 * The chrome's colours, from the same `tokens/` the stylesheet is built from.
 * Hand-written hexes here drifted from the design system silently, because
 * nothing compares a Storybook theme to anything.
 */

export const palette = {
  light: {
    appBg: '#ffffff',
    appContentBg: '#ffffff',
    appPreviewBg: '#ffffff',
    appBorderColor: '#e1e1e6',
    textColor: '#15151a',
    textMutedColor: '#575768',
    textInverseColor: '#fbfbfc',
    barBg: '#ffffff',
    barTextColor: '#575768',
    colorPrimary: '#2068d5',
    colorSecondary: '#2068d5',
    inputBg: '#ffffff',
    inputBorder: '#e1e1e6',
    inputTextColor: '#15151a',
  },
  dark: {
    appBg: '#15151a',
    appContentBg: '#2b2b34',
    appPreviewBg: '#15151a',
    appBorderColor: '#41414e',
    textColor: '#f0f0f2',
    textMutedColor: '#a7a7b4',
    textInverseColor: '#15151a',
    barBg: '#2b2b34',
    barTextColor: '#a7a7b4',
    colorPrimary: '#4688f0',
    colorSecondary: '#4688f0',
    inputBg: '#2b2b34',
    inputBorder: '#41414e',
    inputTextColor: '#f0f0f2',
  },
} as const;

export type ThemeName = keyof typeof palette;
