name: Release

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: write

jobs:
  release-please:
    name: Version and Release
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: node
          target-branch: master
          config-file: release-please-config.json
